### PR TITLE
"Headphones for you" Section Content Alignment Enhancement

### PR DESCRIPTION
**Pull request by iamRabia-N**
This pull request contains the updated code for the  alignment correction. This pull request is the output of the following issue:
**"Headphones for you" Section Content Alignment Enhancement** #561

### CODE REVIEW

**Comment by iamRabia-N** [comment]
@codervivek5 Kindly review this pull request.

**Comment by codervivek5** [comment]
share any output

**Comment by iamRabia-N** [comment]
> share any output

**Before**
op5

**After**
op6

**Comment by codervivek5** [comment]
these are also not aligned check the corner radius is not uniform..???

**Comment by iamRabia-N** [comment]
@codervivek5 The issue is to align the content only so I have worked only on aligning the content of the box. No work is done on box radius from my side.

**Comment by codervivek5** [comment]
> @codervivek5 The issue is to align the content only so I have worked only on aligning the content of the box. No work is done on the box radius from my side.

plz try to fix the basic bug .....if I have assigned these minor issues then it goes to very complicate for me to review PR and merge them

**Comment by iamRabia-N** [comment]
@codervivek5 Done with correction. Commit with id "f89ebc130af574f3ecfdd649edb28ac9c4dc349b" is dealing with radius issue. Here's the output:
ss (2)

Focus only on radius as this commit only includes radius updates. Content alignment solution is in previous commits.

**Comment by codervivek5** [comment]
@iamRabia-N have you check it ....this is already done in the website....so there is no need to add this feature again

**Pull request closed without merging**
