### PR TITLE
Fixed & Upgraded ChatBot

### PR DESCRIPTION
**Pull request by SyedImtiyaz-1**
Hello @codervivek5 ,
I have fixed the ChatBot issue using Advance JS and API,
in future you can access info for the products directly from GPT and this is 100% working.

## Video -
[Screencast from 26-06-23 08:01:26 PM IST.webm](https://github.com/codervivek5/VigyBag/assets/121503426/98091d88-d649-4946-b132-a407abf8d10a)

### It is ready to `Merge` 👍🏻

### CODE REVIEW

**Comment by mehaksharma10** [comment]
@codervivek5  this PR is already merged in 

1. https://github.com/GameSphere-MultiPlayer/GameSphere/pull/660 
2. https://github.com/codervivek5/VigyBag/pull/496 
3. https://github.com/Anupkjha2601/food-recipes-website/pull/423
4. https://github.com/Eduhub-Community/Eduhub-Community.github.io/pull/433
5. https://github.com/Opentek-Org/opentek/pull/374
6. https://github.com/DSC-JSS-NOIDA/blogzen/pull/693

**Comment by mehaksharma10** [comment]
@codervivek5

**Comment by SyedImtiyaz-1** [comment]
@codervivek5 ,
He is just a spammer, who wanted to lose my ranking also he is not even a part of GSSoC 23.
Ask his details before any actions.

**Comment by mehaksharma10** [comment]
@SyedImtiyaz-1 the point if of not following the GSSoC guidelines. You can be banned. You can just take it to Mods on discord. lets see what they will say.

**Comment by mehaksharma10** [comment]
image

 ## Read the 8th point carefully

**Comment by SyedImtiyaz-1** [comment]
@codervivek5 ,
He is just a spammer, who wanted to lose my ranking also he is not even a part of GSSoC 23.
Ask his details before any actions.
btw same goes to you Killer2OP

**Comment by mehaksharma10** [comment]
You have a problem. I dont have any

**Comment by SyedImtiyaz-1** [comment]
> You have a problem. I dont have any

you're a soab.

**Pull request merged**
