### PR TITLE
Signup Page is Done and One Login Issue is also Solved

### LINKED ISSUE #1554: Signup Page is Done and One Login Issue is also Solved
Signup Page is Done and One Login Issue is also Solved

### PR DESCRIPTION
**Pull request by Tanmay-Mirgal**
## Fixes Issue

Fix Issue : #1554
Closes: #1554

## Screenshots

image
image
image
In login page the icon for email is changed it was previous call icon

## Summary by CodeRabbit

- **New Features**
  - Introduced a signup page with a form for new user registration, including inputs for full name, email, password, and terms agreement, as well as social signup options for Google and Facebook.
  - Added a new route for the signup page to the application.

- **Enhancements**
  - Updated the email input icon in the login form to use `MdEmail` from `react-icons/md`.

### CODE REVIEW

**Comment by codervivek5** [comment]
@sanjay-kv As you can see there are many changes in the file but also you have marks it as level 1

**Comment by sanjay-kv** [comment]
as i mentioned there was no discussion prior happened before restoring points, I reduced points after a long discussion with internal team and other admin. looks like  a joke now.

**Comment by sanjay-kv** [comment]
and irony is the contributor has not yet reached out to me, I don't understand why there so much care to one contributor.

**Comment by codervivek5** [comment]
> and irony is the contributor has not yet reached out to me, I don't understand why there so much care to one contributor.


its not about care its about there effort...
you have completely removed the Points...... it is right and you are taking about care 🤷‍♂️

**Comment by Tanmay-Mirgal** [comment]
> and irony is the contributor has not yet reached out to me, I don't understand why there so much care to one contributor.

I really respect your post at gssoc that's why I'm quiet from since mornings , I first contact  the project admin and talk to him  and beacause he told me be quiet and not to talk rudely with you . And I really respect you but it's not like that u can fully have a control on my points I had put my all three months in vigybag and some of them early target me ad I am onlying contributing in vigybag and not contributing in other projects I like to work with vigybag soo why I can't I go ahead with one project is that you guildleness restrict me to do that . And secondly I had a 100 of meetings with the project admin since project admin and build the whole vigybag and acquire the Position in gssoc leaderboard and you are like deducting points like anything like it's a game for you to do

**Comment by Tanmay-Mirgal** [comment]
@sanjay-kv  And there is no personal connections with the project admin first I want to clear that thing if you feel so and you blocked me as you feel me as a spam user that's not completely fair you didn't saw my efforts behind that and you don't have the right to judge me like that soo better don't think that the project admin is caring about me because he is Adding points because you deducted points like nothing making a thought before whether I should I have talk with the user and then I should do so .I'm sorry if my words are not proper but I am really angry on your discussion on deducting my points like 1000 points you deducted like anything only

**Pull request merged**
