### PR TITLE
Android: Implement Dependency Injection 

### PR DESCRIPTION
**Pull request by javaman97**
### #629 Implemented the Dependency Injection

Used **KOIN** as a Dependency Injection Framework

### CODE REVIEW

**Comment by javaman97** [comment]
@07jasjeet Please have a look !

**Comment by 07jasjeet** [comment]
@javaman97 please use the dependencies in the code as well.

**Comment by javaman97** [comment]
@07jasjeet Let me know which dependencies I need to add to the code. Related to Koin,I already added it in build.gradle module

**Comment by 07jasjeet** [comment]
Please "inject" the dependencies as well.

This is what I mean:

1) Remove the following line https://github.com/codervivek5/VigyBag/blob/a336eeea1cc5a53363ce33b2781a84baa7a9ce0a/Android/app/src/main/java/com/vigbag/android/viewmodel/ProductViewModel.kt#L8 
And then do this:
   ```kotlin
   class ProductViewModel (private val productRepository) : ViewModel() {
   ``` 

2) With this done, then at the following line:
https://github.com/codervivek5/VigyBag/blob/9805d35f6c4b6acbaf94611f719750ddb553c32b/Android/app/src/main/java/com/vigbag/android/ui/home/HomeFragment.kt#L25
Replace with following code snippet:
   ```kotlin
   private val viewModel by viewModel<ProductViewModel>()
   ``` 
   while also removing the following line: https://github.com/codervivek5/VigyBag/blob/a336eeea1cc5a53363ce33b2781a84baa7a9ce0a/Android/app/src/main/java/com/vigbag/android/ui/home/HomeFragment.kt#L38

And you should be good.

**Comment by javaman97** [comment]
[VigyBag/Android/app/src/main/java/com/vigbag/android/di/AppModule.kt](https://github.com/codervivek5/VigyBag/blob/a336eeea1cc5a53363ce33b2781a84baa7a9ce0a/Android/app/src/main/java/com/vigbag/android/ui/home/HomeFragment.kt#L38)

11      ProductViewModel(get())

Need to update this line like this

**Comment by javaman97** [comment]
@07jasjeet I have made the changes as described. Please have a look!

**Comment by 07jasjeet** [comment]
Lgtm thanks for the work!

**Pull request merged**
