### PR TITLE
Updated Product-PopUp Section

### PR DESCRIPTION
**Pull request by SyedImtiyaz-1**
Hello @codervivek5 ,
Issue No. #695 
Previously it was reverted by mistake I have raised a new PR and done the changes as per your conditions.

### Video - 
[Screencast from 29-07-23 10:23:49 PM IST.webm](https://github.com/codervivek5/VigyBag/assets/121503426/4170e5ce-363b-4ee4-be9e-b5bbb3de314d)

### You can review this. 👍🏻

### CODE REVIEW

**Comment by codervivek5** [comment]
bro description is missing.....if there is no space then at least write two lines only for the description only

**Comment by SyedImtiyaz-1** [comment]
> bro description is missing.....if there is no space then at least write two lines only for the description only

Okay Adding

**Comment by SyedImtiyaz-1** [comment]
@codervivek5 Added Desc too.

## Screenshot 
image

**Comment by SyedImtiyaz-1** [comment]
@codervivek5

**Review by codervivek5 — APPROVED** [review]

**Comment by codervivek5** [comment]
perfect 👍 🥇 


kindly solve conflict then I will merge your PR

**Comment by SyedImtiyaz-1** [comment]
@codervivek5 You can merge this now it is ready to Merge 👍🏻

**Review by codervivek5 — APPROVED** [review]

**Comment by SyedImtiyaz-1** [comment]
@codervivek5 Resolving

**Comment by codervivek5** [comment]
I thing some other candidate also working in this file that is the reason this conflict again occured....kindly solve it once again then i will merge it first

**Comment by SyedImtiyaz-1** [comment]
Resolving give me a min.

**Review by codervivek5 — APPROVED** [review]

**Comment by codervivek5** [comment]
image
Nothing solved bro

**Comment by SyedImtiyaz-1** [comment]
@codervivek5 Check now

**Comment by codervivek5** [comment]
kindly check it once bro....I have revert it at this time ...after check all the file structure make again PR then I will merge it

**Comment by SyedImtiyaz-1** [comment]
okay @codervivek5

**Pull request merged**
