### PR TITLE
Progress bar overlaps navbar fixed

### LINKED ISSUE #1834: progress bar and navbar co-incide
the green line of progress bar overlaps the navbar and when scrolled till bottom it hide a portion of navbar which doesn look very appealing, i can fix this add necsarry padding so that it looks appropriate even when scrolled down , kindly assign this to me 
Screenshot 2024-07-15 222016

### PR DESCRIPTION
**Pull request by Priyal208**
## Fixes Issue

fixes #1834 

## Changes proposed

The progrss bar earlier overlapped navbar and hid some portion of navbar, I gave appropriate padding and fixed it so that overlapping is fixed

## Screenshots

Screenshot 2024-07-16 205245

## Note to reviewers

You can see that overlap is now gone

## Summary by CodeRabbit

- **New Features**
  - Introduced a responsive UserNavbar component that enhances navigation with user authentication, search capabilities, and dynamic dropdown menus.
  - Added a mobile-friendly toggle for navigation links, improving usability on smaller devices.
  
- **Style**
  - Improved navigation bar padding for better spacing on small screens.

### CODE REVIEW

**Comment by Priyal208** [comment]
@codervivek5 kindly review this

**Comment by codervivek5** [comment]
fix merge conflict

src/components/Navbar/UserNavbar .jsx 

remove extra space from the file name
- UserNavbar .jsx     to        UserNavbar.jsx 


share any image or video for review your changes

**Comment by codervivek5** [comment]
pull the code first

**Comment by Priyal208** [comment]
@codervivek5 i have attached the image in the pr desc pl check

**Comment by Priyal208** [comment]
@codervivek5 now pls check

**Comment by Priyal208** [comment]
@codervivek5 review this pls now

**Comment by Priyal208** [comment]
@codervivek5 what about this pr pls check

**Comment by Priyal208** [comment]
@codervivek5 I have 3PRs pending to be reviewed since last 1 week, pls look into that

**Comment by Priyal208** [comment]
@codervivek5 MERGE THIS, its been a week im trying to get a review, i have 3PRS pending to be reviewed, pls look into that

**Comment by Priyal208** [comment]
@codervivek5 add gssoc label and level to this, its not counted in my gssoc points its been 3 days

**Pull request merged**
