### PR TITLE
fixing search bar

### PR DESCRIPTION
**Pull request by dhritiluthra**
#107 
fixed search bar padding
added pointer cursor to search button
removed the inner border

here it is

Screenshot (40)

### CODE REVIEW

**Comment by codervivek5** [comment]
kindly attach the output so that I can review

**Comment by dhritiluthra** [comment]
> kindly attach the output so that I can review

I attached it. please check

**Comment by codervivek5** [comment]
kindly solve the merge conflict.

**Comment by codervivek5** [comment]
any update?

**Comment by dhritiluthra** [comment]
done

**Comment by codervivek5** [comment]
its already submitted by another candidate.....kindly you can go through another issue

**Pull request closed without merging**
