### PR TITLE
Fixed home page responsive

### PR DESCRIPTION
**Pull request by Somesh-Mallewar**
Hello @codervivek5,
### IT IS READY TO `MERGE`

### CODE REVIEW

**Comment by codervivek5** [comment]
make some changes in new update. for it you can pull the code the make the changes

**Comment by Somesh-Mallewar** [comment]
Hello @codervivek5 ,
I have maintained the code in the PR please check it once and it is read to `MERGE`

**Comment by codervivek5** [comment]
kindly show me your output so that I can review your issue and if there will any required changes then I will tell you also

**Comment by Somesh-Mallewar** [comment]
Here is the video :- 
@codervivek5 ,

https://github.com/codervivek5/VigyBag/assets/118499404/207e516f-6abc-4eae-a5c2-849c671fad57

**Comment by codervivek5** [comment]
Pull the code once then solve the merge conflict then I will merge your PR

**Comment by Somesh-Mallewar** [comment]
Hello @codervivek5 

Conflict Resolved

**Comment by codervivek5** [comment]
hello @Somesh-Mallewar kindly pull the code and resolve the bug 

after solve the conflict ...drop a message on discord..then I will merge your PR after Review

**Comment by ParthMadhvani2** [comment]
hey @codervivek5 please assign this issue to me I solved it and sent a pull request.

**Comment by Somesh-Mallewar** [comment]
@codervivek5 I have solved just give me some time i will pull the code

**Comment by Somesh-Mallewar** [comment]
@codervivek5 ,
Conflicts resolved

**Comment by codervivek5** [comment]
someone make some changes in this file that is the reason again conflict occured.....first you pull the code then solve conflit

**Comment by Somesh-Mallewar** [comment]
@codervivek5 I have changed the codebase

**Comment by codervivek5** [comment]
bro can you share any recent output  ??

**Pull request closed without merging**
