### PR TITLE
add: mobile menu

### PR DESCRIPTION
**Pull request by Gurnav224**
Mobile menu added

### CODE REVIEW

**Comment by codervivek5** [comment]
kindly show me output so that i can review

**Comment by Gurnav224** [comment]
https://github.com/codervivek5/VigyBag/assets/72142482/769fa245-05ef-4bb1-9258-0c72b054ed0c

**Comment by codervivek5** [comment]
I like it .....Thankyou for your contribution

kindly solve the merge conflict but try to pull the code so that it will easy for your to make changes with new code

**Comment by Gurnav224** [comment]
Ok I will fix it

**Comment by codervivek5** [comment]
ok @Gurnav224  I am waiting

**Comment by Gurnav224** [comment]
Subject: New Pull Request - feat: mobile menu #624


I've submitted a new pull request for the "feat/mobile-menu" feature branch (#624). Kindly review the changes and provide your feedback.



Unfortunately, I lost all my code while pulling, so I re-implemented the feature and conducted thorough testing to ensure functionality and compatibility.

**Comment by codervivek5** [comment]
I have merge your PR which you mention in the comment.
I think this PR now not usable so I should close it ???

**Pull request closed without merging**
