### PR TITLE
Added styles to the about us page #1168

### LINKED ISSUE #1168: Adding styles to the about us page
Adding styles to the about us page
@codervivek5 Please assign me this under GSSoC 2024

### PR DESCRIPTION
**Pull request by SuhainaFathimaM**
## Fixes Issue
Closes #1168 

## Changes proposed

1. corrected footer of the about Page
2. Turned off text selection
3. added copyrights selection
4. added payments image
5. added colour to button
6. added hovering effect to button
7. Changed the content for header
8. Added style for the header topic
9. Changed the description content
10. Added style to description
## Screenshots
image
image

## Note to reviewers

@codervivek5 I am contributing under GSSoC24 .. Please assign me this PR under GSSoC and label this PR

### CODE REVIEW

**Comment by codervivek5** [comment]
kindly show me any screen shot or nay video so that i can review it

**Comment by SuhainaFathimaM** [comment]
@codervivek5 I have added the screenshots

**Comment by codervivek5** [comment]
Image is not looking good can you Plz change this image ?

**Comment by SuhainaFathimaM** [comment]
@codervivek5 Do I need to improve the styling ??

**Pull request closed without merging**
