### PR TITLE
Home Page is Done

### PR DESCRIPTION
**Pull request by Tanmay-Mirgal**
## Fixes Issue
Fix Issue:#1466
Closes:#1466

## Screenshots

image
image
image
image

## Summary by CodeRabbit

- **New Features**
  - Enhanced `CategoryCard` for improved clarity in prop naming and responsive design.
  - Refactored `LatestInMarketCard` to accept a single `product` object, streamlining data management.
  - Updated routing configuration to improve error handling for unmatched routes.
  - Revamped `Home` component with a new layout, updated image imports, and structured data arrays for better organization.

- **Bug Fixes**
  - Improved error handling within the routing to guide users more effectively.

- **Style**
  - Introduced Tailwind CSS for enhanced responsiveness and aesthetics in the `Home` component.

### CODE REVIEW

**Comment by codervivek5** [comment]
@sanjay-kv why you have decreased the level....kindly let me know first if you find any issues like spam.

if that will spam then I'll close and delete the PR except decrease the level.


there is so much research behind the development of these pages. if you need any proof then let me know I'll share with you.


but till then do cut then the points

**Comment by sanjay-kv** [comment]
image


first of its too late to mention why I reduce labels. 

i have mentioned access cvia emails and other mediums multiple times, and event tagged you on multiple issues. 

you are not following the guidelines while labelling. there are level3 label for multiple responsive prs.

**Comment by sanjay-kv** [comment]
https://github.com/GSSoC24/Contributor/discussions/517
check this page

**Comment by sanjay-kv** [comment]
image


this i not just for this contributors.

**Comment by codervivek5** [comment]
yea, I have read all the messages and replies also if you don't then please take a look the these well-mannered people who is contributing to GSSOC and completely unfollow the GSSOC guidelines.

image

**Comment by codervivek5** [comment]
@sanjay-kv you why they are frustrated like this because they are raising unnecessary issues in VigyBag and I have not assigned them.

as you are the Program manager then I hope you will do everything fare. kindly do not break my trust in GSSOC because I have spend continuously 3 year as a contributor and project admin also

**Comment by codervivek5** [comment]
this is also a sample of our effort. where we will discuss the idea and then execute 
image

**Comment by sanjay-kv** [comment]
I have reported this comments to GitHub by flagging . It was inside thread untagged. 
We have taken continuous effort maintaining decorum as you might have seen many people tried similar conversation and we banned from program. 
I have noticed this now and banned from discussion

**Pull request merged**
