### PR TITLE
Navbar Issue Fixed

### LINKED ISSUE #2283: Navbar Getting Fixed at Top
The navbar is getting fixed on the top and not showing the content of the page. I can solve this issue.

@codervivek5 Please assign me this issue. Please add gssoc-ext and hacktober-accepted labels.

### PR DESCRIPTION
**Pull request by Archisman141**
## Fixes Issue

Closes #2283

## Changes proposed

The navbar is getting fixed at the top and on scrolling down it hides the contents below, so I have fixed this issue.

##Screenshot

Screenshot 2024-10-12 224341

Before on scroll down the page

Screenshot 2024-10-12 224444

After on scroll down the page

## Summary by CodeRabbit

- **New Features**
	- Introduced new XML configuration files for improved project management, including `deploymentTargetSelector.xml`, `gradle.xml`, `misc.xml`, `modules.xml`, and `vcs.xml`.
	- Enhanced change tracking functionality in the IDE.
  
- **Improvements**
	- Updated the `UserNavbar` and `Navbar` components to use sticky positioning for better user experience while scrolling.

- **Bug Fixes**
	- Adjusted paths and settings in the configuration files to reflect the current project structure.

- **Chores**
	- Added entries to `.gitignore` to exclude user-specific files from version control.

### CODE REVIEW

**Comment by Archisman141** [comment]
@codervivek5 Please review and merge my PR

**Comment by codervivek5** [comment]
Show me any screenshot so that I can take a look of your changes

**Comment by Archisman141** [comment]
> Show me any screenshot so that I can take a look of your changes

@codervivek5 I have add the ss please check it and merge it.

**Comment by Archisman141** [comment]
@codervivek5 Please review and merge my PR

**Comment by Archisman141** [comment]
@codervivek5 Please merge my PR

**Comment by Archisman141** [comment]
@codervivek5 Please merge my PR

**Review by codervivek5 — APPROVED** [review]

**Comment by Archisman141** [comment]
@codervivek5   Please add level

**Pull request merged**
