### PR TITLE
Home Page UI (Issue #1068)

### PR DESCRIPTION
**Pull request by Anuja1227**

### CODE REVIEW

**Comment by codervivek5** [comment]
Kindly mention issue number

**Comment by dhruv389** [comment]
hello @codervivek5 , 

### i have made home page  in  Front with-React-js folder. (According to new figma design )
### Can you checkout this pull request : https://github.com/codervivek5/VigyBag/pull/1105#issue-2304760733

**Comment by codervivek5** [comment]
Thankyou for your contribution 🤗

**Comment by codervivek5** [comment]
@dhruv389 we have make some changes for more information join today's meeting at 10pm

**Pull request merged**
