### PR TITLE
Fixed the website 

### PR DESCRIPTION
**Pull request by Sch476**
Fixes issue #805 

Video : 

https://github.com/codervivek5/VigyBag/assets/127319225/89320716-a8c4-4922-816a-087016922903

I fixed the index.html and removed the excess code . It will fix the Problem in the homepage. 👍🏼

Thank You.

### CODE REVIEW

**Comment by Sch476** [comment]
Hello @codervivek5 I fixed the website. The code was stacked, multiple index.html was stacked. For that reason the code was jammed. I fixed it. You can safely merge this PR into the main branch.

Thank You.

**Comment by codervivek5** [comment]
kindly solve rhe conflict so that i can review and before make the pr pull the code

**Comment by codervivek5** [comment]
dark mode is not working

**Comment by Sch476** [comment]
Kar toh raha hai bro kaam Dark mode : 


https://github.com/codervivek5/VigyBag/assets/127319225/63e052df-95c0-4dee-bc65-1c845a3d41b2

**Pull request merged**
