### PR TITLE
added effects to the fashion and accessories section

### LINKED ISSUE #21: Add some effects to the fashion and accessories section
I want to add some effects to this section to make it more attractive.

image

### PR DESCRIPTION
**Pull request by rolikaagarwal**
closes #21 

Before- 

before

After- 

https://github.com/codervivek5/VigyBag/assets/81984963/67b6d7bc-69d3-42e6-b33e-e2ab2fea0350

### CODE REVIEW

**Comment by codervivek5** [comment]
kindly add this effect only in a rectangle shape and add the hover effect in the text.

**Comment by rolikaagarwal** [comment]
I've added the hover effect to the rectangle box and a different effect to the text.

After- 

https://github.com/codervivek5/VigyBag/assets/81984963/9ea16c59-2abe-4411-9c92-3c155616bd34

**Comment by codervivek5** [comment]
@rolikaagarwal plz add this effect in both if I hover in the rectangle box then the effect will be shown in both text and the rectangle in the same time and if I hover in intext then same as the rectangle box and reduce the distance between the box and text.

**Comment by rolikaagarwal** [comment]
Reduced the distance between text and box. Added hover effect as suggested.


https://github.com/codervivek5/VigyBag/assets/81984963/11091d37-8b07-4d9d-9d61-ea2b214d679e

**Comment by codervivek5** [comment]
> Reduced the distance between text and box. Added hover effect as suggested.
> 
>  changed.mp4

perfect 👍

**Comment by codervivek5** [comment]
Thanks for contribution :)

**Pull request merged**
