### PR TITLE
Redesign the new testimonial

### PR DESCRIPTION
**Pull request by parasss19**
## Description
- Re Design whole new Testimonials section
- Added animation
- No need of review.css and review.js file as all the code are in index.html file 

## Light Mode 

https://github.com/codervivek5/VigyBag/assets/101205226/e75b0a0c-1274-4e92-b974-8bfdb3b7794a

## Dark Mode

https://github.com/codervivek5/VigyBag/assets/101205226/b3a02b83-43a8-4ceb-b70f-7b9982522557

### CODE REVIEW

**Comment by parasss19** [comment]
@codervivek5 Please review it

**Comment by codervivek5** [comment]
can you make a little bit of change in it.....make blue these color for the card when it will not in dark mode......overall design is pretty good 👍 

this one https://user-images.githubusercontent.com/101205226/257797986-e75b0a0c-1274-4e92-b974-8bfdb3b7794a.mp4

**Comment by codervivek5** [comment]
make gradient color white and bluish

**Comment by parasss19** [comment]
## @codervivek5  This gradient is looking good the UI of the website and suite on both light and dark mode


https://github.com/codervivek5/VigyBag/assets/101205226/cd855f4a-a931-47da-95ea-1abae4a3a55a

**Comment by codervivek5** [comment]
bro can you make some more changes on it....change name color to blue ( logo color) and start color to green

**Pull request closed without merging**
