### PR TITLE
Item section updated.

### PR DESCRIPTION
**Pull request by Pragati-3003**
I have changed the UI of the item section of the website .
If you would like any changes , please let me know.
Thanking You.

### CODE REVIEW

**Comment by codervivek5** [comment]
kindly solve merge conflict

**Comment by codervivek5** [comment]
any update

**Comment by Pragati-3003** [comment]
I have resolved all the issues.I kindly request you to review these modifications .

**Comment by codervivek5** [comment]
due to some other PR conflicts occurring again. kindly solve it and let me know then I will merge it.

**Comment by codervivek5** [comment]
kindly mention your issue number at PR time

**Comment by Pragati-3003** [comment]
> kindly mention your issue number at PR time

okie

**Comment by Pragati-3003** [comment]
I have resolved all the merge conflicts.

**Comment by codervivek5** [comment]
Actually, due to PR changes, it occurred again.

kindly solve it once then I will merge it.

**Comment by Pragati-3003** [comment]
> Actually, due to PR changes, it occurred again.
> 
> kindly solve it once then I will merge it.

okie.
Also, I request you to assign GSSOC tag and level to this issue.

**Comment by codervivek5** [comment]
Actually, due to PR changes, it occurred again.

kindly solve it once then I will merge it.

**Comment by Pragati-3003** [comment]
> Actually, due to PR changes, it occurred again.
> 
> kindly solve it once then I will merge it.

i have solved once again kindly check and inform me.

**Comment by codervivek5** [comment]
@Pragati-3003 plz show me your changes like any screenshot or any video so that I can review

**Comment by Pragati-3003** [comment]
> @Pragati-3003 plz show me your changes like any screenshot or any video so that I can review
IMG_20230526_231641

Kindly inform me if you want any changes.

**Comment by codervivek5** [comment]
you make it more good

Thank you for your contribution :)

**Comment by codervivek5** [comment]
kindly tell me your issue number if you remember.

**Pull request merged**
