### PR TITLE
added styles to contact page

### LINKED ISSUE #564: UI of contact page
Need to change the UI of contact Page , please assign me this under gssoc'23

Screenshot (133)

### PR DESCRIPTION
**Pull request by krutikajichkar**
fixed #564

### CODE REVIEW

**Comment by codervivek5** [comment]
can you share any output so that  I can review

**Comment by krutikajichkar** [comment]
@codervivek5 sure , here you go

**Comment by codervivek5** [comment]
screenshot is not visible @krutikajichkar

**Comment by krutikajichkar** [comment]
Screenshot (173)

**Comment by codervivek5** [comment]
everything is perfect but if can you remove bottom scroll bar then it will completely looking amazing

**Comment by krutikajichkar** [comment]
@codervivek5 yes , i can do that

**Comment by codervivek5** [comment]
Let  me know after make this change I will merge this PR.....kindly don't forget to add output of your change

**Comment by krutikajichkar** [comment]
Screenshot (174)
@codervivek5 please review this

**Comment by codervivek5** [comment]
perfect 👍

**Review by codervivek5 — APPROVED** [review]

**Pull request merged**
