### PR TITLE
Android: Search Bar

### LINKED ISSUE #611: Android: Search Bar
# Problem
Currently search bar of android app is inoperable. The search bar should be used to search for products available on VigyBag.

# Action
The search bar should be able to show results by querying a remote database through an API endpoint, but since the server is not live yet, fake or mock data must be used to populate search results.

### LINKED ISSUE #666: Android: Fix app-wide theme
# Problem
Currently, the theme and colors of VigyBag have no definition or structure what so ever. This means that whenever switching between themes, the colors have inconsistent behaviour.

# Action
Add appropriate colors to VigyBag Theme and use it app-wide.

### PR DESCRIPTION
**Pull request by javaman97**
https://github.com/codervivek5/VigyBag/assets/75328768/44c30d3b-7325-4f4e-8f11-a5c0f0fb0210

### Search Bar Functionality Added 
1) Using MVVM Architecture (ViewModel, Repository)
2) Circular ImageView Library Added for Product Image 
Reference:-  https://github.com/hdodenhof/CircleImageView

### CODE REVIEW

**Comment by javaman97** [comment]
@07jasjeet Please have a look !

**Comment by 07jasjeet** [comment]
Alright, thanks for mentioning the issue number but next time do it in the description itself with header formatting.
For the code changes, these mostly look good but I would like you to refactor the code you just wrote with appropriate spacing and new lines. The XML layouts and the logic code, both lack spacing and make the code look bad. Also refactor all the with whitespaces and new lines while you're at it.

**Comment by javaman97** [comment]
Thanks @07jasjeet,I would do the same as you suggested by mentioning the issue number next time.
For now,I would add proper spacing in both Xml and logic code,then I hope we are good to go.

**Comment by 07jasjeet** [comment]
> Thanks @07jasjeet,I would do the same as you suggested by mentioning the issue number next time. For now,I would add proper spacing in both Xml and logic code,then I hope we are good to go.

Also, when switching themes, the UI seems to have inconsistent behaviour with colors. Please make sure it is top notch :)

**Comment by javaman97** [comment]
@07jasjeet Please have a look and let me know of further changes. For theming we have another issue, we will fix it over there.

**Comment by 07jasjeet** [comment]
> @07jasjeet Please have a look and let me know of further changes. For theming we have another issue, we will fix it over there.

As discussed, darker backgrounds for dark mode and VigyBag default light colors for light mode. Also fixing status bar and nav bar will do aswell.

**Comment by 07jasjeet** [comment]
Linking another issue because it covers that as well.

**Comment by javaman97** [comment]
### Fixed Issue  #666
https://github.com/codervivek5/VigyBag/assets/75328768/ca6fe34b-a085-4cf9-962c-b715f75050ac

**Comment by javaman97** [comment]
@07jasjeet Please have a look! I have added the Light & Dark Theming app-wide

**Comment by 07jasjeet** [comment]
> @07jasjeet Please have a look! I have added the Light & Dark Theming app-wide

Nice work, lgtm.

**Pull request merged**
