### PR TITLE
modify the navbar

### PR DESCRIPTION
**Pull request by parasss19**
## Description
- Redesign the navbar

## Screenshot

https://github.com/codervivek5/VigyBag/assets/101205226/d1d7a2c0-abea-4325-be9c-6bc23bd07af4

### CODE REVIEW

**Comment by parasss19** [comment]
Hey @codervivek5 Please review it

**Comment by codervivek5** [comment]
bro make some changes.......give it length 100% and fixed it in top....then share the output

**Comment by parasss19** [comment]
Hey @codervivek5 Review it now


https://github.com/codervivek5/VigyBag/assets/101205226/405fd859-ef82-4003-bafd-275e107a83f9

**Comment by codervivek5** [comment]
> Hey @codervivek5 Review it now
> 
>  VigyBag._.Home.-.Google.Chrome.2023-07-30.21-40-14_Trim.mp4

why you change the color bro... the previous color was looking good ...pinkish type color

**Comment by codervivek5** [comment]
leave it simple bro...it is looking good ....if you can work in backend then feel free to  try with django

**Comment by parasss19** [comment]
> > Hey @codervivek5 Review it now
> > VigyBag._.Home.-.Google.Chrome.2023-07-30.21-40-14_Trim.mp4
> 
> why you change the color bro... the previous color was looking good ...pinkish type color

Check now

**Comment by parasss19** [comment]
> leave it simple bro...it is looking good ....if you can work in backend then feel free to try with django

I am frontend guy don't know very much about django I am learning nodejs

**Comment by codervivek5** [comment]
can you share any output ?

**Comment by parasss19** [comment]
> can you share any output ?



https://github.com/codervivek5/VigyBag/assets/101205226/97f65506-db21-45ce-859f-f6b4577b37dd

**Comment by codervivek5** [comment]
it is not looking good bro....

**Comment by parasss19** [comment]
> it is not looking good bro....

I think you can set it's color according to your choice easily

**Comment by codervivek5** [comment]
website theme color is good for it...if you can then plz try it  once

**Comment by parasss19** [comment]
> website theme color is good for it...if you can then plz try it once

Want exact same color?

**Comment by codervivek5** [comment]
yes

**Comment by parasss19** [comment]
> yes

i checked the exact same color but it was not looking good so i changed it check the recent one

**Comment by parasss19** [comment]
> > yes
> 
> i checked the exact same color but it was not looking good so i changed it check the recent one


https://github.com/codervivek5/VigyBag/assets/101205226/f9e456fb-e894-4edc-910f-64e4821b3e5f

**Comment by codervivek5** [comment]
image
have you use this color for the navigation???

**Comment by parasss19** [comment]
> image have you use this color for the navigation???

No

**Comment by codervivek5** [comment]
just try in once and don't remove transparency look

**Comment by parasss19** [comment]
> just try in once and don't remove transparency look

Done

https://github.com/codervivek5/VigyBag/assets/101205226/33258d49-e14e-4a86-96bd-4a89af876df4

**Comment by codervivek5** [comment]
bro can you convert it like this with transparency effect

**Pull request closed without merging**
