### PR TITLE
Header Updated 

### PR DESCRIPTION
**Pull request by teeshaa**
Updated the header where the brand logo was not visible before.

Solves issue #622

### CODE REVIEW

**Comment by codervivek5** [comment]
you can enhance this About Us page like make some changes to it 
- remove smit and shift the below text in this place
- change the image of the about us page
- replace about us vigybag with about us only in a single line and change the text color with the theme color 
- use the navbar from the index.html file that is better from this one

**Comment by codervivek5** [comment]
after make these changes kindly share a screen shot with me so that i can review it

**Comment by krutikajichkar** [comment]
@teeshaa this was my issue how did you made a PR for that ,@codervivek5 can you please explain what just happend

**Comment by codervivek5** [comment]
@krutikajichkar don't worry....let me check it once I will assign it to you If is eligible for this

**Comment by codervivek5** [comment]
@teeshaa you can only make PR only in your issue or if I assign you any issue...this is against the GSSOC polity so I have to close this PR but you can continue with another issue

**Pull request closed without merging**
