### PR TITLE
back to top button added

### PR DESCRIPTION
**Pull request by purviporwal1812**
https://github.com/codervivek5/VigyBag/assets/116807722/87b467ac-0388-462a-be32-99f1fa251fad

#206

### CODE REVIEW

**Comment by codervivek5** [comment]
can you add this icon a little bit above?

also, solve the merge conflict so that I can merge it.

**Comment by purviporwal1812** [comment]
I have made the required change

**Comment by codervivek5** [comment]
kindly solve merge conflict and make required changes.

**Comment by codervivek5** [comment]
can I see your changes??

**Comment by purviporwal1812** [comment]
https://github.com/codervivek5/VigyBag/assets/116807722/7cfa0db5-8a9e-4ecc-9383-2f5263e0dada

**Comment by codervivek5** [comment]
I suggest you that pulling the code once otherwise your changes affect the whole website then make your PR so  then I will review it and merge it

**Comment by codervivek5** [comment]
after pulling the code do not remove code that is not useful for you

**Pull request closed without merging**
