### PR TITLE
Fixed Horizontal Overflow Error

### PR DESCRIPTION
**Pull request by abhi03ruchi**
Resolved Issue #222,  bug leading to overflow of website content.

### CODE REVIEW

**Comment by codervivek5** [comment]
solve merge conflict.

**Comment by codervivek5** [comment]
Solve merge conflict

**Comment by codervivek5** [comment]
kindly fix it again after pull the code also solve merge conflict....then I will merge your PR

**Comment by ParthMadhvani2** [comment]
hey, @codervivek5 I had fixed this issue of horizontal overflow please accept my pull request as I am a GSSoC'23 contributor.
I have already sent a pull request.

**Comment by codervivek5** [comment]
actully many contributor in working in same issue that is the reason you face this problem again and again

**Comment by codervivek5** [comment]
This issue is already fixed

**Pull request closed without merging**
