### PR TITLE
Resolve About page and fix bug

### PR DESCRIPTION
**Pull request by Meenal21i**

### CODE REVIEW

**Comment by codervivek5** [comment]
Kindly show me output so that I can review your PR ....also mentioned your issue number

**Comment by Meenal21i** [comment]
The output is that on the main index i have added a button to navigate to about section, when we click on that button we are redirected to the about page which is also added by me. 

A screen capture is added for your reference:

[vigybag_about.webm](https://github.com/codervivek5/VigyBag/assets/116749181/a5264444-15c7-4bd5-b54b-2b2a4d6fb6f8)

**Comment by Meenal21i** [comment]
Kindly condider the demo video of about page and button added and please merge the pull request.@codervivek5

**Comment by codervivek5** [comment]
Hello @Meenal21i There is already a about us If your can improve then go through that

**Comment by codervivek5** [comment]
Is issue already fixed

**Pull request closed without merging**
