### PR TITLE
Bug report #724 resolved

### PR DESCRIPTION
**Pull request by Manishak798**
I added new local storage and re-write the whole JS program, now when the dark mode is turned on it does not get disabled after refreshing the page or clicking on any button.

### CODE REVIEW

**Comment by Manishak798** [comment]
image
Do check my PR, and let me know about the same.

**Comment by codervivek5** [comment]
kindly solve merge conflict then I will merge your PR

**Review by codervivek5 — APPROVED** [review]

**Comment by Manishak798** [comment]
Hey @codervivek5 I resolved the conflicts please view my PR.

**Comment by codervivek5** [comment]
again conflict occur due to the multiple candidates working the same file

**Comment by Manishak798** [comment]
hey @codervivek5  I have solved the merge conflicts kindly check my PR.

**Comment by Manishak798** [comment]
Hey @codervivek5 please check my PR.

**Comment by Manishak798** [comment]
hey @codervivek5 kindly check my PR.

**Comment by Manishak798** [comment]
Hey @codervivek5 please view my PR.

**Comment by codervivek5** [comment]
actually many contributors is working in the same file that is the reason the conflict occured again.
can you please solve it once again

**Comment by Manishak798** [comment]
Hey @codervivek5 I have resolved the conflicts please view my PR

**Comment by Manishak798** [comment]
I have resolved the merge conflicts

**Comment by Manishak798** [comment]
Hey, @codervivek5 kindly check my PR I again solved the merge conflicts.

**Comment by Manishak798** [comment]
Hey @codervivek5 kindly check my PR.

**Comment by Manishak798** [comment]
Hey @codervivek5 I request you to check my PR as tomorrow is the last day of GSSOC.

**Comment by Manishak798** [comment]
Hey @codervivek5 kindly check my PR.

**Comment by codervivek5** [comment]
I am really sorry to face this problem again.
actually many contributors is working in the same file that is the reason the conflict occured again.

**Comment by Manishak798** [comment]
> I am really sorry to face this problem again. actually many contributors is working in the same file that is the reason the conflict occured again.

No worries, I resolved it Kindly check my PR.

**Comment by Manishak798** [comment]
Hey, @codervivek5 kindly check my PR as I resolved merge conflicts.

**Comment by Manishak798** [comment]
Hey @codervivek5 kindly review my PR request.

**Comment by Manishak798** [comment]
Hey @codervivek5 Kindly check my PR as tomorrow is the last day of GSSOC23.

**Comment by Manishak798** [comment]
Hey @codervivek5 kindly view my PR.

**Comment by codervivek5** [comment]
it' tooo much 😢...can you resolve it ???

**Comment by Manishak798** [comment]
> it' tooo much 😢...can you resolve it ???

Sure, I am doing it right now

**Comment by Manishak798** [comment]
Hey @codervivek5 I have solved the merge conflicts, Please view my PR.

**Comment by Manishak798** [comment]
Hey, @codervivek5 kindly check my PR before merge conflicts as tomorrow is the last day of GSSOC23, I hope you understand my concern.

**Comment by codervivek5** [comment]
i will merge this PR but if anything will be unstructured then I will revert it .....ok

**Comment by Manishak798** [comment]
> i will merge this PR but if anything will be unstructured then I will revert it .....ok

Okie Kindly review my code and just tell me if there is anything that is unstructured. I am willing to do the corrections.

**Pull request merged**
