### PR TITLE
dynamic navbar added

### PR DESCRIPTION
**Pull request by Ansh101112**
## Fixes Issue
#1643 

## Summary by CodeRabbit

- **New Features**
  - Added confirmation dialog for logout using `window.confirm`.
  - Introduced logout functionality and conditional rendering based on login status in the Navbar.

- **Bug Fixes**
  - Corrected local storage key for logout functionality to "isLoggedin".

- **Improvements**
  - Enhanced error messages and logging for better clarity during logout.
  - Updated form submission handling in the Login page for improved performance and reliability.

### CODE REVIEW

**Comment by bhuvangoel04** [comment]
Your merged PR has created a new issue.
Screenshot 2024-07-02 234738
You moved the event listeners outside of the tag.

**Comment by Ansh101112** [comment]
> Your merged PR has created a new issue.
> Screenshot 2024-07-02 234738
> You moved the event listeners outside of the tag.

Where?

**Comment by Ansh101112** [comment]
> > Your merged PR has created a new issue.
> > Screenshot 2024-07-02 234738
> > You moved the event listeners outside of the tag.
> 
> Where? 

Connect me on discord

**Comment by bhuvangoel04** [comment]
> Connect me on discord

Send me your username

**Comment by bhuvangoel04** [comment]
copy
 
> > Where?

**Comment by Ansh101112** [comment]
> 
> > Connect me on discord
> 
> Send me your username
> 

tanshuman145

**Pull request merged**
