### PR TITLE
Added hover effect to footer text and social icons

### LINKED ISSUE #13: Adding Hover Effect to the footer and the social media links
I want to add some hover effects to the footer. 

image

### PR DESCRIPTION
**Pull request by rolikaagarwal**
closes #13 

Added Hover effect 

https://github.com/codervivek5/VigyBag/assets/81984963/75231343-d33f-4d0b-bc45-0e2e94d10e82

### CODE REVIEW

**Comment by codervivek5** [comment]
have you added this hover effect for the Quick menu section?

**Comment by rolikaagarwal** [comment]
@codervivek5 Yes, I've added in the quick links section too.

**Comment by codervivek5** [comment]
ok

**Comment by codervivek5** [comment]
Thanks for contributing.

**Pull request merged**
