### PR TITLE
checkout page added

### PR DESCRIPTION
**Pull request by Tushar98644**
Screenshot 2023-05-24 at 9 19 40 PM
Screenshot 2023-05-24 at 9 19 43 PM

### CODE REVIEW

**Comment by Tushar98644** [comment]
pls review @codervivek5

**Comment by codervivek5** [comment]
make the width 70 to 80% and change the button color to blue type.

**Comment by Tushar98644** [comment]
> make the width 70 to 80% and change the button color to blue type.

updated

Screenshot 2023-05-25 at 2 29 49 PM

**Comment by Tushar98644** [comment]
@codervivek5 any updates?

**Review by JigarJoshi04 — APPROVED** [review]
LGTM

**Comment by Tushar98644** [comment]
@codervivek5 @JigarJoshi04 updates?

**Pull request closed without merging**
