### PR TITLE
Updated 4 product to 5 product

### PR DESCRIPTION
**Pull request by Gaurang-Agrawal1**
I have updated the code . please merge it

### CODE REVIEW

**Comment by codervivek5** [comment]
kindly send me the output so that I can review it.

**Comment by Gaurang-Agrawal1** [comment]
Screen shot of output-

Screenshot (2541)
Screenshot (2541)
Screenshot (2543)
Screenshot (2544)
Screenshot (2545)
Screenshot (2546)

@codervivek5 your full site output is here please review it and merge it.

**Comment by Gaurang-Agrawal1** [comment]
I have made changes to the issue of spelling mistake (from card to ---->> cart )
please merge it.
Issue #89

**Comment by codervivek5** [comment]
kindly mention your issue number at PR time.

**Comment by Gaurang-Agrawal1** [comment]
I

> I have made changes to the issue of spelling mistake (from card to ---->> cart ) please merge it. Issue #89

issue-->> #89

**Comment by codervivek5** [comment]
bro, what is the issue number for PR #88?

**Comment by Gaurang-Agrawal1** [comment]
@codervivek5 you assigned me the 2 issues 
No-1- Issue is to make product 4 to 5  which I have done so please merge it. (issue #88  ) issue #88 is updated code for products 
No-2- Issue is for the spelling mistake of card(card-->> cart) which I also corrected (issue #89)

**Comment by Gaurang-Agrawal1** [comment]
> @codervivek5 you assigned me the 2 issues No-1- Issue is to make product 4 to 5 which I have done so please merge it. (issue #88 ) issue #88 is updated code for products No-2- Issue is for the spelling mistake of card(card-->> cart) which I also corrected (issue #89)

Also when you assign the issue to make product 4 to 5 it has issue no #9 but when I update the code it become issue #88

**Comment by codervivek5** [comment]
kindly solve conflict

**Comment by Gaurang-Agrawal1** [comment]
> kindly solve conflict

Ok , I am working on it.

**Comment by codervivek5** [comment]
ok

**Comment by Gaurang1602** [comment]
hey!!! @codervivek5 I have made the changes it showing this option 
Screenshot (2551)
does I have to commit to main branch or I will create new branch

**Comment by Gaurang-Agrawal1** [comment]
I have commited the changes and resolve the issue

**Comment by Gaurang-Agrawal1** [comment]
> I have commited the changes and resolve the issue

So, please merge it.

**Comment by Gaurang-Agrawal1** [comment]
@codervivek5 please merge my PR of issue #88

**Comment by Gaurang-Agrawal1** [comment]
@codervivek5 please merge my PR for issue #88 also please reply on it if there is some problem

**Comment by Gaurang-Agrawal1** [comment]
I have checked or review my code you can also see it here :- 

Page1 -

Screenshot (2552)

Page 2-

Screenshot (2553)

Page 3-

Screenshot (2554)

Page 4-

Screenshot (2555)

Page 5-

Screenshot (2556)

Page 6-

Screenshot (2557)


So, please merge it

**Comment by codervivek5** [comment]
bro kindly solve the conflict and tell kindly contact me ...due to some other merge conflict will have occurred.

you can connect with me throw LinkedIn or discord also.

**Comment by Gaurang-Agrawal1** [comment]
@codervivek5  I have sent you connection request so please accept it ,name - Gaurang.

**Comment by codervivek5** [comment]
Bro solve it one last time after it I will merge your PR first

**Comment by codervivek5** [comment]
@Gaurang1602 kindly solve the merge conflict .....actually, many contributors is working on the same issue that's why this is occurred.


your work is great

**Comment by codervivek5** [comment]
This issue already fix

**Pull request closed without merging**
