### PR TITLE
#87 : Added styling to scroll bar

### PR DESCRIPTION
**Pull request by harshitakaushik-dev**
### Features 👍 
- Styling of the scroll bar is done to match the theme and color scheme of the website
- Additional functionality of changing the color of the scroll bar on hover.

### Preview :
preview

Thank you :)

### CODE REVIEW

**Comment by codervivek5** [comment]
perfect.

Thank you for contribution :)

**Comment by codervivek5** [comment]
Have and issue.
Actully your changes are not reflected after merge you PR ?

**Comment by harshitakaushik-dev** [comment]
The changes are clearly reflected on my local site and I can see the
changes commited in the files submitted at the time of PR.

Can you help me out a little on this?

**Comment by codervivek5** [comment]
let me check once again.

**Comment by codervivek5** [comment]
I also can't understand why changes are not reflected after the merge...just create a new PR then try.

**Comment by harshitakaushik-dev** [comment]
Hey, I just checked out the website and luckily,
The changes are reflected there. The hover effect is functional as well. 
I hope this means that the issue is resolved. 

Attaching image from the webpage and NOT my local code.
checked

**Comment by codervivek5** [comment]
I think due to the network glitch, I can't show the reflection.

Thank you for your contribution :)

**Pull request merged**
