### PR TITLE
Login Page created according to the Figma Style #Issue18

### PR DESCRIPTION
**Pull request by Saumya40-codes**
Issue no: 18
Made login page wrt to the Figma style

With this issue in the current code: in index.html and CSS file, there were some merge conflicts, I've tried to fix that 
image

Also, in the items-description, there was a problem 
prob

I have fixed that as well.

Here is the final output

https://github.com/codervivek5/VigyBag/assets/115284013/413ff12c-bf09-46aa-8e24-74e8b6ed6bca

### CODE REVIEW

**Comment by codervivek5** [comment]
try to solve merge conflict

**Comment by Saumya40-codes** [comment]
The code I'm having has no conflicts, should I replace the existing code with it?

**Comment by Saumya40-codes** [comment]
@codervivek5 i think merge conflict is fixed now according to current code

**Comment by codervivek5** [comment]
no its not fix till now.

**Comment by codervivek5** [comment]
when you fix the conflict then kindly contact me on LinkedIn or Discord so that I will merge your PR first...


remember 1 thing that does not make any changes in another file try to update all the today's also so that the project file will be updated with current changes.

**Comment by codervivek5** [comment]
after fixing the issue and after making PR kindly, share your repo with me so that I can check it once.

**Pull request closed without merging**
