### PR TITLE
Resize 'home page' and make it responsive #849

### LINKED ISSUE #849: Resize 'home page' and make it responsive
look at the home page of the website there is so much unwanted space which makes website user experience bad 
- Reduced height of each section
- Fix color according to theme color, You can get figma link to know more about website color theme.

### PR DESCRIPTION
**Pull request by Hacxmr**
## Fixes Issue

Closes #849

## Changes proposed
1. Altered the height of various container 
2. Changes made to the color and style
3. UI enhancement
4. overflowing issue resolved

## Screenshots
image

## Note to reviewers
I have made significant changes to the home page. kindly review and suggest if any other improvement can be done.

### CODE REVIEW

**Comment by codervivek5** [comment]
it seems like this is very congested like there is very minimum space among the elements its to reduced the size of element so that it feel pretty

**Comment by Hacxmr** [comment]
> it seems like this is very congested like there is very minimum space among the elements its to reduced the size of element so that it feel pretty
@codervivek5 may I know which component of the home page you are talking about? whether it's the search box or the list items

**Comment by codervivek5** [comment]
reduced the image size which i have share in screenshot and also reduced the size of text so that it will look like good and attractive

**Comment by Hacxmr** [comment]
@codervivek5 May I get the screenshot?

**Comment by codervivek5** [comment]
screenshot is same as given above

**Comment by codervivek5** [comment]
which you have shared

**Pull request closed without merging**
