### PR TITLE
added footer and navbar in login page

### LINKED ISSUE #700: Add navigation bar and footer  in home page login button

### PR DESCRIPTION
**Pull request by krutikajichkar**
fixed #700 
closes #700 

Screenshot (212)
Screenshot (213)

### CODE REVIEW

**Comment by krutikajichkar** [comment]
@codervivek5 please review my PR

**Comment by krutikajichkar** [comment]
Screenshot (214)

**Comment by codervivek5** [comment]
New Microsoft PowerPoint Presentation
can you convert it like this...I will level up this issue to **level3**

**Comment by codervivek5** [comment]
make this login form as a pop-up form when user click in the login button

**Comment by krutikajichkar** [comment]
@codervivek5 okay , I will try

**Comment by krutikajichkar** [comment]
@codervivek5 can i change the design of login form , actually when I am trying to use this in popup it is breaking all way , there is too much CSS for just a login form . What I will do is I will just remove the right side of the login form written "Hello Friends" and will provide option for signUp in signIn itself. Let me know your suggestions

**Comment by codervivek5** [comment]
> @codervivek5 can i change the design of the login form , actually when I am trying to use this in the popup it is breaking all away, there is too much CSS for just a login form . What I will do is I will just remove the right side of the login form written "Hello Friends" and will provide an option for signUp in signIn itself. Let me know your suggestions

ok, you can try it as you feel comfortable but do not change CSS and HTML file names...if there will be a need for a js file then name it "login.js" like this

**Comment by krutikajichkar** [comment]
https://github.com/codervivek5/VigyBag/assets/93243210/13e65c09-b86a-4159-9575-4b8a91454f56

@codervivek5 please have a look

**Comment by codervivek5** [comment]
kindly solve the conflict then I will merge it

**Comment by krutikajichkar** [comment]
@codervivek5 conflicts has been resolved

**Comment by codervivek5** [comment]
its again occur due to the multiple candidates contributions

**Comment by krutikajichkar** [comment]
@codervivek5 stay there I am resolving them

**Comment by krutikajichkar** [comment]
@codervivek5 please check now

**Comment by codervivek5** [comment]
I am so sorry for the late...solve it once and drop a msg. firstly I will merge your PR.

**Comment by krutikajichkar** [comment]
@codervivek5  can you check now?

**Comment by codervivek5** [comment]
Thank you for you contribution

**Pull request merged**
