### PR TITLE
text BEST SELLER added

### PR DESCRIPTION
**Pull request by whizzy23**
I added the text best seller and corrected spelling of cart in clothes section

### CODE REVIEW

**Comment by codervivek5** [comment]
kindly solve merge conflict and try to show whole image so that I can understand  your changes better

**Comment by whizzy23** [comment]
I have resolved the merge conflict 
EARLIER

AFTER ADDING BEST SELLER text

**Comment by codervivek5** [comment]
do not add best sellers like this..remove it its not looking good.

**Comment by whizzy23** [comment]
Ok... I am closing the issue and this pull request

**Pull request closed without merging**
