### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by harshsingh32**
This pr is made under issue #121.

### CODE REVIEW

**Comment by codervivek5** [comment]
kindly show me your changes so that I can review and review your PR

**Comment by harshsingh32** [comment]
I have some changes in the readme file to make it more expressive.

**Comment by codervivek5** [comment]
so kindly show me changes

**Comment by harshsingh32** [comment]
Screenshot_2023-05-26-21-58-12-23_40deb401b9ffe8e1df2f1cc5ba480b12
Screenshot_2023-05-26-21-58-26-00_40deb401b9ffe8e1df2f1cc5ba480b12

**Comment by harshsingh32** [comment]
please review and merge the pr

**Review by codervivek5 — APPROVED** [review]

**Comment by codervivek5** [comment]
Thankyou for contribution :)

**Pull request merged**
