### PR TITLE
Added Services

### PR DESCRIPTION
**Pull request by SyedImtiyaz-1**
Hello @codervivek5 .
## Issue No. #449 
Added services page. 

## Video - 
[Screencast from 22-06-23 01:58:23 PM IST.webm](https://github.com/codervivek5/VigyBag/assets/121503426/1f8efa71-dcde-4d70-9a0b-23aa62f856e6)

### It is ready to merge. 👍🏻

### CODE REVIEW

**Comment by codervivek5** [comment]
solve merge conflict and no need to add this much things for about us.....this is an e-commerce website so add services according to the e-commerce site,..,,,.,.. not this much

**Comment by SyedImtiyaz-1** [comment]
@codervivek5  Sure I'll make more familier to E-Commerce

**Comment by SyedImtiyaz-1** [comment]
### Conflicts Resolved ! @codervivek5

**Comment by codervivek5** [comment]
can your show me your changes

**Comment by SyedImtiyaz-1** [comment]
> can your show me your changes

Sure.

**Comment by SyedImtiyaz-1** [comment]
Hello @codervivek5 ,
Here is the change - 

## Video - 
[Screencast from 22-06-23 11:49:16 PM IST.webm](https://github.com/codervivek5/VigyBag/assets/121503426/7d9ee731-28e1-4505-b221-14ce83a7b56c)


## Screenshot - 
Screenshot from 2023-06-22 23-51-55

### It is ready to merge 👍🏻

**Pull request merged**
