### PR TITLE
Android: UI improved

### LINKED ISSUE #567: Android: Improve sign-up and sign-in UI
Sign-up / sign-in fragments could use some UI improvements in VigyBag Android App.

### PR DESCRIPTION
**Pull request by essy16**
->Added passwordToggleEnabled
> Added Google,Twitter and facebook icons
-> Changed the background

![WhatsApp Image 2023-07-18 at 23 55 07 (1)]
![WhatsApp Image 2023-07-18 at 23 55 07]
@07jasjeet please review

### CODE REVIEW

**Comment by 07jasjeet** [comment]
@essy16 you images are not visible and you have conflicts with the main branch. Please resolve them and then we can move ahead. If you need any help, ping me.

**Comment by essy16** [comment]
@07jasjeet which conflicts if I may ask...I'll also check the margins and try to change them accordingly

**Comment by 07jasjeet** [comment]
> @07jasjeet which conflicts if I may ask...I'll also check the margins and try to change them accordingly

@essy16 merge conflicts. There's an error on your pr look carefully.

**Comment by essy16** [comment]
@07jasjeet I've pushed some changes

**Comment by essy16** [comment]
@07jasjeet

**Comment by 07jasjeet** [comment]
> @07jasjeet

@essy16 you still need to resolve the merge conflicts. Please refer [GitHub docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github) for this purpose. It'll be good if you know how to resolve conflicts. This skill is a basic need in any corporation you work with. Just take your time reading the document because I can assure you it 100% covers your case.

image

**Comment by essy16** [comment]
I have done so...kindly check @07jasjeet

**Comment by 07jasjeet** [comment]
> I have done so...kindly check @07jasjeet

@essy16 At least make sure you are right before tagging me because there's still conflicts. Just give this time and solve this problem. This is software dev as well and make no rush I can create plenty of issues whenever you want.

**Comment by essy16** [comment]
image
@07jasjeet please check

**Comment by 07jasjeet** [comment]
@essy16 Idk what you want me to look at but all I'm saying that there's merge conflicts showing here which means I just can't merge your work because even GitHub won't allow me to do so. You have two solutions now : 

1) Solve merge conflicts with the help of the link I provided in the above conversation or go watch a Youtube video on it.
2) Create a new pr with updated main and changes done on top of it.

Also please use command line or GitHub desktop and not this IDE integrated one.

**Comment by essy16** [comment]
image @07jasjeet I have done so according to the Docs and it's not showing me about Merge conflicts please guide me ...I have also watched Youtube videos about it and I have made some changes

**Comment by 07jasjeet** [comment]
> image @07jasjeet I have done so according to the Docs and it's not showing me about Merge conflicts please guide me ...I have also watched Youtube videos about it and I have made some changes 

Setup a meet at 1 or 2pm IST.

**Comment by essy16** [comment]
@07jasjeet https://meet.google.com/aak-obnw-fae here is the meeting link @1pm IST

**Comment by essy16** [comment]
@07jasjeet please don't forget about the meeting

**Pull request closed without merging**
