### PR TITLE
Navbar & Footer in About page

### LINKED ISSUE #594: Navbar and footer
I would like to add proper footer and navbar in about page.

### PR DESCRIPTION
**Pull request by BhartiNagpure**
#594 

close #594 

I'm added Navbar and Footer to the about page.

### CODE REVIEW

**Comment by codervivek5** [comment]
can you share any output ??

**Comment by BhartiNagpure** [comment]
> can you share any output ??

sure
Screenshot 2023-07-17 230347
Screenshot 2023-07-17 230401

**Comment by BhartiNagpure** [comment]
> > can you share any output ??
> 
> @codervivek5 here is output
 Screenshot 2023-07-17 230347 Screenshot 2023-07-17 230401

**Comment by codervivek5** [comment]
is this page link to the about which is in navigation bar??

**Comment by BhartiNagpure** [comment]
> is this page link to the about which is in navigation bar??

Yes

**Review by codervivek5 — APPROVED** [review]

**Pull request merged**
