### PR TITLE
Added png design

### PR DESCRIPTION
**Pull request by Ks103**
@codervivek5 I designed the payment design according to the website , If there are any changes please tell or any other design you want tell me i'll design it. Also if you like the design please merge y my pr.
 
Here is the ss of the design

Screenshot 2023-05-25 223432

### CODE REVIEW

**Comment by codervivek5** [comment]
make some basic changes only your design looking like pretty.
- make a corner rounder of each Input.
- wrap all the fields in a container if you wrap then try to change the background color to something like the user profile if you refer to Figma design which is present in the readme file.

**Comment by Ks103** [comment]
hey @codervivek5  I have updated designs in payment design folder there are 2 designs, please check if any changes needed let me know.
Here are the designs ,

Group 2
Group 1

**Comment by codervivek5** [comment]
Thank you for your contribution :)

**Comment by Ks103** [comment]
Thankyou @codervivek5 sir

**Pull request merged**
