### PR TITLE
Reviewer section added

### LINKED ISSUE #373: Create : Reviewer section.
I would like to add the reviewer section for the website. So, please assiggn this issue to me under GSSOC'23.

### PR DESCRIPTION
**Pull request by Pragati-3003**
I have added a reviewer section for the website .
Please merge and inform me if you wanna any other changes.
Fixes #373
Screenshot 2023-06-22 192412

### CODE REVIEW

**Comment by codervivek5** [comment]
@Pragati-3003 you can make some color changes according to the figma file ....you can get that file from the readme.md


Also, could you solve the merge conflict? When you work on it before work kindly pull the code once and then work so that the occurred conflict can be reduced.

**Comment by Pragati-3003** [comment]
> @Pragati-3003 you can make some color changes according to the figma file ....you can get that file from the readme.md
> 
> Also, could you solve the merge conflict? When you work on it before work kindly pull the code once and then work so that the occurred conflict can be reduced.

Screenshot 2023-06-22 231303
is this fine?
and I'll resolve all the conflicts.

**Comment by codervivek5** [comment]
image
change color something like this

**Comment by codervivek5** [comment]
do not change text ...........only change color

**Comment by Pragati-3003** [comment]
> image change color something like this

okie

**Comment by codervivek5** [comment]
do not change text which you write that is ok ............only change color according to my pic

**Comment by Pragati-3003** [comment]
> do not change text which you write that is ok ............only change color according to my pic

Screenshot 2023-06-23 003947
Is this ok now.

**Comment by codervivek5** [comment]
solve the conflict....and also share output so that i can see and give you proper feedback

**Comment by Pragati-3003** [comment]
> solve the conflict....and also share output so that i can see and give you proper feedback

image
@codervivek5 , check this and lemme know if you want any other changes.

**Comment by codervivek5** [comment]
Kindly solve merge conflict

**Comment by Pragati-3003** [comment]
> Kindly solve merge conflict

@codervivek5 , I have resolved all the merge conflicts please check.

**Pull request merged**
