### PR TITLE
Update index.html for redirection

### PR DESCRIPTION
**Pull request by Swarnim-Chandve**
Updated index.html of "Services" to redirect to product container section .

### CODE REVIEW

**Comment by codervivek5** [comment]
kindly solve merge conflict then I will merge it

**Comment by Swarnim-Chandve** [comment]
Sir , I solved the merge conflict , now please kindly merge my pull request .

**Comment by codervivek5** [comment]
show me the output so that I can merge your PR also mention your issue number related to this issue.

**Comment by Swarnim-Chandve** [comment]
Sir how to show the output ? I am confused

**Comment by Swarnim-Chandve** [comment]
https://github.com/codervivek5/VigyBag/assets/112816781/0096b241-7192-41ca-9c5d-44fc93bc5374

**Comment by Swarnim-Chandve** [comment]
can this be called a output ?

**Comment by Swarnim-Chandve** [comment]
image
this is the issue number #202

**Comment by codervivek5** [comment]
bro fix this website. this is not looking good.

try to clone it once more then try to make changes.

**Comment by codervivek5** [comment]
this issue already solved

**Pull request closed without merging**
