### PR TITLE
Fixed #487

### LINKED ISSUE #487: create a side navbar
i am a gssoc23 contributor . pleaase assign this issue to me @codervivek5 
image
similar to this example

### PR DESCRIPTION
**Pull request by ePSA-eJya**
#487 
fixed

please review and merge the pr

@codervivek5

### CODE REVIEW

**Comment by ePSA-eJya** [comment]
please review and merge the pr

@codervivek5

**Comment by codervivek5** [comment]
can I see your output ??

**Comment by ePSA-eJya** [comment]
https://github.com/codervivek5/VigyBag/assets/120899038/d7b2bb62-c3a3-4c7a-a8b2-0583931218c3

**Comment by codervivek5** [comment]
bro it's not looking good..... try to fix this hamburger 
- remove VigyBag as title 
- make text size little bit small

after complete these task you can share your changes first if all things will perfect then make PR for merge

**Comment by ePSA-eJya** [comment]
> bro it's not looking good..... try to fix this hamburger
> 
> * remove VigyBag as title
> * make text size little bit small
> 
> after complete these task you can share your changes first if all things will perfect then make PR for merge

ok

**Comment by ePSA-eJya** [comment]
image
 
what about this??? @codervivek5

**Pull request closed without merging**
