### PR TITLE
Added scroll effects

### PR DESCRIPTION
**Pull request by 7twik**
added on scroll effects

### CODE REVIEW

**Comment by codervivek5** [comment]
kindly show me output

**Comment by 7twik** [comment]
Will i make a video and attach it here?

**Comment by codervivek5** [comment]
I can't see your video kindly solve merge conflict to that I can mere but first of all show me output plz

**Comment by 7twik** [comment]
https://github.com/codervivek5/VigyBag/assets/99895046/ac76ec72-8d59-453c-a8a6-93e51d62e9b2

Resolved the conflict..and here is the output ...kindly check it @codervivek5

**Comment by codervivek5** [comment]
Thank you for your contribution.

**Comment by codervivek5** [comment]
kindly close the issue related to this PR. so that you can got your full points.

**Pull request merged**
