### PR TITLE
Sign In Page

### PR DESCRIPTION
**Pull request by ojaswi18**
This is code for the Django template of Sign In page. I have also made the required changes in login page to connect it to the sign in page. Kindly preview and merge. @codervivek5 
Screenshot (126)

### CODE REVIEW

**Comment by codervivek5** [comment]
is this properly working ??

**Comment by ojaswi18** [comment]
> is this properly working ??
I have merely overridden the default signup page keeping all the links same.

**Comment by codervivek5** [comment]
ok so I have merged it

**Comment by codervivek5** [comment]
can you collaborate with me to complete this project after the GSSSOC will be over ???

**Comment by ojaswi18** [comment]
> can you collaborate with me to complete this project after the GSSSOC will be over ???

I would be happy to be a part of VigyBag team even after GSSOC but won't be apple to contribute after 5th of September since I will get busy with my college work.

**Pull request merged**
