### PR TITLE
Footer Changes #1169

### LINKED ISSUE #1169: footer at the team page need to improved
footer at the team page need to improved
@codervivek5 Please assign me this under GSSoC 2024

### PR DESCRIPTION
**Pull request by SanaAzeem512**
Closes #1169

https://github.com/codervivek5/VigyBag/issues/1169

### CODE REVIEW

**Comment by codervivek5** [comment]
kindly share the change which you have made

**Comment by SanaAzeem512** [comment]
IN TEAM FOLDER 
1.Changed in team.html 
-Organized the footer into clear sections: About Us, Quick Links, and Social.
-Added appropriate class names and semantic tags.

2.In team.css (CSS Styling):
-Ensured proper spacing and padding for better visual separation.
-Styled links and icons for improved appearance.

The updated code improves the footer's layout, alignment, and visual appearance  and proper HTML structure. Adjust the image and link paths as necessary.

**Comment by codervivek5** [comment]
Va you Plz share your change via photo or screenshot pr screen recorder

**Comment by SanaAzeem512** [comment]
Screenshot (461)

**Review by codervivek5 — APPROVED** [review]

**Pull request merged**
