### PR TITLE
Update style.css and Add space around search bar

### PR DESCRIPTION
**Pull request by ArunMaramraj**
The style.css has been updated to add space around the search bar

### CODE REVIEW

**Comment by codervivek5** [comment]
kindly so me the output so that I can verify it.

**Comment by ArunMaramraj** [comment]
image
hello @codervivek5. Thanks for responding !   Added top margin space for the button and aligned it to center. It looks like this now.. do tell me if any more changes are required.. Thank you!

**Comment by codervivek5** [comment]
kindly mention your PR number

**Comment by ArunMaramraj** [comment]
hello @codervivek5 . Could you help me where i can find the PR number

**Comment by codervivek5** [comment]
it's my mistake Actually I want to know about the issue number. You have to mention the issue number at PR time.

**Comment by ArunMaramraj** [comment]
image

Hello @codervivek5.. is this what you wanted? It shows #36 below opened issue here

**Comment by codervivek5** [comment]
dude when i assign it to you then you was working in under a issue so I want to know that issue number

**Comment by codervivek5** [comment]
> image
> 
> Hello @codervivek5.. is this what you wanted? It shows #36 below opened issue here

this is PR number and I want issue number

**Comment by ArunMaramraj** [comment]
IMG_20230522_003547
I'm sorry. It shows #8 as you can see in the image

**Comment by codervivek5** [comment]
ok ok ......maybe It's would be my mistake

**Pull request merged**
