### PR TITLE
What Do Our Costumers Say Page Improvement DONE

### PR DESCRIPTION
**Pull request by Swapnita06**
#980 
FIXES ISSUE

Changes proposed:-
I have made the necessary changes to improve the professionalism of the website.

BEFORE THE CHANGES : -
BEFORE-1
BEFORE-2

AFTER THE CHANGES :-
AFTER THE CHANGES

Done the necessary improvements for the review page.

### CODE REVIEW

**Comment by codervivek5** [comment]
one last change if possible add atleast 5 reviews at a time in a single line and make it look like caraousel so that we can slide to see more reviews

**Comment by Swapnita06** [comment]
@codervivek5 Sir I thought of carousel but actually the whole page contains carousel....so i think carousel may not look good in customer review page.

**Comment by codervivek5** [comment]
ummmm 🤔

ok I think if you add the latest 5 reviews in a line so it will look better. what are you saying is it right?

**Comment by Swapnita06** [comment]
Sir I guess 5 reviews in a single line may look a bit clumsy and smaller. I think three in a line is may be a bit more spacious and tidy.

**Comment by codervivek5** [comment]
Thankyou for your contributions :)

**Pull request merged**
