### PR TITLE
feat: Added Multiple  Workflow Files in workflows Sub-Folder in .github Parent Folder

### PR DESCRIPTION
**Pull request by NarendraKoya999**
## Changes proposed
- **Added close_old_issues.yml, issues.yml, linting.yml, lock.yml and prevent_multiple_issues.yml Files in workflows Sub-Folder in .github Parent Folder for Using Different Purposes.** 

## Note to reviewers
- **Basis on My Issue, I did not add deno.yml File. Because of we don't need for Our Project Requirements like Languages Used Point of View.**

### CODE REVIEW

**Comment by NarendraKoya999** [comment]
Hi @codervivek5 . Please Review on this PR. In future Point of View, these 5 Files are very helpful for Issues and PR's. So, Kindly add Valid Level Label under GSSOC'23. Thank You !

**Comment by codervivek5** [comment]
image


image
what is it mean???

**Comment by NarendraKoya999** [comment]
> 
> image
> 
> 
> image
> what is it mean???

I did not understand to why this check fail.Please give me any help OR Suggestion.Because of i have no depth knowledge on that Issue.

**Comment by NarendraKoya999** [comment]
Hi @codervivek5 . Please check PR once Again. This time No Checks Fails. Actual Error is I did not Update my Branch in My Remote Repository.

**Comment by NarendraKoya999** [comment]
Hi @codervivek5 . Please Take Action on this PR?

**Comment by codervivek5** [comment]
again same issue.
image

**Comment by NarendraKoya999** [comment]
> again same issue. image

@codervivek5 . I cross Check Finally. After My Changes Made. I will Contact You. Thank You !

**Comment by NarendraKoya999** [comment]
@codervivek5 . I have Installed prettier and Add prettierrc.json File. Please Check?. If It's not work , Please Disable that Workflow. Thank You !

@codervivek5 Any Update on this ?

**Comment by codervivek5** [comment]
image
what shoud I do ?

**Comment by codervivek5** [comment]
image

**Comment by NarendraKoya999** [comment]
> image what shoud I do ?

Please Remove Linting related File and Remains Please Merged @codervivek5

**Comment by codervivek5** [comment]
image
can i desable it ??

**Comment by NarendraKoya999** [comment]
> image can i desable it ??

Yes Disable It @codervivek5

**Comment by codervivek5** [comment]
again same issue
image

**Comment by NarendraKoya999** [comment]
> again same issue image

Only Linting Workflow Problem is There @codervivek5 ?

**Comment by codervivek5** [comment]
yes

**Comment by NarendraKoya999** [comment]
> yes

Ok @codervivek5 . Please Ignore that Feature and Merged Remain workflows If it is no Problems There.

> yes

**Pull request merged**
