### PR TITLE
Updated Footer

### PR DESCRIPTION
**Pull request by Sameep002**
Screenshot 2023-05-23 163649

updated footer!!

### CODE REVIEW

**Comment by codervivek5** [comment]
try to solve the merge conflict and make some changes like the uniformity of each section like quick link, contact us, and social 
they are not uniform 
so kindly try to make some changes to it

**Comment by codervivek5** [comment]
any update?

**Comment by Sameep002** [comment]
will make those changes before tmrw night!!, also in pull request we have to select main branch or create new branch?

**Comment by codervivek5** [comment]
try to create a new branch you  can see development branch in this official repo

**Comment by Sameep002** [comment]
Screenshot 2023-05-25 203618

@codervivek5 is this uniform??

**Pull request closed without merging**
