### PR TITLE
Add Hover Effect to Wishlist Icon of Product Card # 162

### PR DESCRIPTION
**Pull request by rissh**
Hey @codervivek5 ,
Please review the following output and please let me know if there are any updates to be made.

https://github.com/codervivek5/VigyBag/assets/87235655/fd339643-2194-4c37-8fea-91095e34c65a

### CODE REVIEW

**Comment by rissh** [comment]
Done with all merge conflicts and now you can see the branch has no conflicts so far. Please merge it and let me know if there are any changes.

**Comment by codervivek5** [comment]
I think another candidate is also working on the same issue that why the conflict occurred again.
try to solve it once and plz let me know when you solve it.

**Comment by rissh** [comment]
Hey @codervivek5 , 
solve the latest conflict. Please let me know if there are any further changes.

**Comment by codervivek5** [comment]
try to mention your issue number in next PR.

After merge this PR kindly close the Issue number related to this PR.

**Comment by codervivek5** [comment]
thankyou for contribution

**Pull request merged**
