### PR TITLE
 added spaces on header button

### PR DESCRIPTION
**Pull request by khushbumaheshwarii**
Close issue #466 
Done some space related  changes for header buttons 
**before**
image
 **After**
image

### CODE REVIEW

**Comment by khushbumaheshwarii** [comment]
@codervivek5 please review my PR

**Review by JigarJoshi04 — APPROVED** [review]

**Comment by khushbumaheshwarii** [comment]
@codervivek5  can please review and merge the PR

**Comment by khushbumaheshwarii** [comment]
@JigarJoshi04 can pls merge my PR?

**Comment by khushbumaheshwarii** [comment]
@codervivek5  can you please merge this PR

**Pull request merged**
