### PR TITLE
Footer Updated

### PR DESCRIPTION
**Pull request by parasss19**
## Changes proposed
- Decreased the size of the footer
- improve the ui 
- Also added animations

## Screenshots
Screenshot 2023-10-02 205700

### CODE REVIEW

**Comment by codervivek5** [comment]
have you added a border radius for top-right corner in the footer section ?

**Comment by parasss19** [comment]
> have you added a border radius for top-right corner in the footer section ?

yes if you want i can remove it

**Comment by parasss19** [comment]
Screenshot 2023-10-03 174108


## @codervivek5 Review it now

**Comment by parasss19** [comment]
@codervivek5 Please review it asap

**Review by codervivek5 — APPROVED** [review]

**Comment by codervivek5** [comment]
Thankyou for your contribution :) @parasss19

**Pull request merged**
