### PR TITLE
Fixed Product Wishlist Behavior

### PR DESCRIPTION
**Pull request by tayyab-ilyas**
## Changes proposed

- Added a wishlist button with an onclick attribute for changing its color when clicked.

- Implemented the changeColor(event) JavaScript function to handle the wishlist button click and change its color to red.

- Modified the changeColor function to fill the SVG with red, in addition to changing the stroke.

- Addressed the issue where clicking on one wishlist button was affecting others, by passing a unique identifier to the changeColor function and updating the color of the specific button that was clicked. 

## Screenshots

Screenshot 2023-08-07 232553

### CODE REVIEW

**Comment by tayyab-ilyas** [comment]
hey @codervivek5 check this out! please don't forget to add the Gssoc'23 label. Thanks!

**Comment by codervivek5** [comment]
sure....kindly solve the merge conflict then  I will merge it

**Comment by tayyab-ilyas** [comment]
check now @codervivek5 is it okay?

**Comment by tayyab-ilyas** [comment]
> sure....kindly solve the merge conflict then I will merge it

please have a look now, I've resolved the conflicts @codervivek5

**Comment by tayyab-ilyas** [comment]
please check @codervivek5

**Comment by codervivek5** [comment]
.kindly solve the merge conflict then I will merge it.....;plz drop a msg in any social network then I will merge your PR first

**Comment by tayyab-ilyas** [comment]
> .kindly solve the merge conflict then I will merge it.....;plz drop a msg in any social network then I will merge your PR first

have resolved them @codervivek5

**Comment by tayyab-ilyas** [comment]
Gssoc is about to be over please merge this soon @codervivek5

**Comment by codervivek5** [comment]
kindly solve the merge conflict then I will merge it

**Comment by tayyab-ilyas** [comment]
> kindly solve the merge conflict then I will merge it

I've solved so many times but you keep merging other PRs before this one thats why it keeps getting conflicts :(

**Comment by tayyab-ilyas** [comment]
I've resolved the conflicts again but if you merge other PR before this it will have conflicts again. @codervivek5 please merge this first and please merge this today as its the last day of Gssoc'23

**Pull request merged**
