### PR TITLE
Added Contact Us Page

### LINKED ISSUE #349: Create a separate Contact Us Page with the website design
Clicking on the Contact us doesn't navigate to anywhere. I would like to create a separate Contact Us page for users to interact

image

### PR DESCRIPTION
**Pull request by PoulavBhowmick03**
Issue #349 
Close #349 
Added a Contact Us page with neumorphism design, adhering to the navbar and footer or the vigybag website

image

### CODE REVIEW

**Comment by PoulavBhowmick03** [comment]
@codervivek5
@JigarJoshi04 
 Check Out

**Comment by PoulavBhowmick03** [comment]
Also, is it possible to label it level 3 for the css design? :"))

**Comment by codervivek5** [comment]
https://www.figma.com/file/hXcM6chTK70O6rAqCTFxuc/Vigy?node-id=0%3A1&t=px6VNjlFCos5Ll9z-1

check this link. Try to use this design for login and signup page

**Comment by PoulavBhowmick03** [comment]
image

Is this okay? since this is the contact us page, haven't added any other stuffs
@codervivek5

**Review by PoulavBhowmick03 — COMMENTED** [review]
changed the background to the theme

**Comment by PoulavBhowmick03** [comment]
@codervivek5

**Review by JigarJoshi04 — APPROVED** [review]

**Comment by codervivek5** [comment]
Kindly solve merge conflict then I will merge it

**Comment by PoulavBhowmick03** [comment]
Hey @codervivek5 Conflict resolved. Please check and merge this.

**Comment by PoulavBhowmick03** [comment]
@codervivek5 kindly merge this so that I can make a PR for other issues

**Comment by PoulavBhowmick03** [comment]
@codervivek5 Hey I have resolved the issue

**Comment by codervivek5** [comment]
bro kindly make a new PR so that conflict can be solved

**Comment by PoulavBhowmick03** [comment]
Okay sure

**Pull request closed without merging**
