### PR TITLE
Home Button Working

### PR DESCRIPTION
**Pull request by Killer2OP**
### Description
Made the Home button working.

### CODE REVIEW

**Comment by codervivek5** [comment]
Show me output so that I can review

**Comment by codervivek5** [comment]
@Killer2OP any update?

**Comment by Killer2OP** [comment]
I am currently at college. So , I will give you output in the evening.

**Comment by Killer2OP** [comment]
**After Changes**

https://github.com/codervivek5/VigyBag/assets/111378171/b630a129-487e-46d6-b224-eded8dccd453

**Comment by codervivek5** [comment]
Thank you for contribution :)

**Pull request merged**
