### PR TITLE
changed the margin and padding of the section and within the section.

### PR DESCRIPTION
**Pull request by PrachiChauhan23**
#104

### CODE REVIEW

**Comment by PrachiChauhan23** [comment]
sir i updated the changes again to resolve the conflict.

**Comment by codervivek5** [comment]
@PrachiChauhan23 kindly show me your output so that I can review your change, how can I know what you changed?

so plz add these sections in every pr 

- Issue number
- your output

I think another person also working in the same file which is why the conflict has occurred again.
 kindly solve it then I will merge it.

**Comment by PrachiChauhan23** [comment]
Screenshot 2023-05-24 103204

**Comment by PrachiChauhan23** [comment]
image

**Comment by PrachiChauhan23** [comment]
image

**Comment by PrachiChauhan23** [comment]
image

**Comment by PrachiChauhan23** [comment]
image

**Comment by PrachiChauhan23** [comment]
image

**Comment by PrachiChauhan23** [comment]
image

**Comment by PrachiChauhan23** [comment]
image

**Comment by PrachiChauhan23** [comment]
image

**Comment by PrachiChauhan23** [comment]
image

**Comment by PrachiChauhan23** [comment]
image

**Comment by PrachiChauhan23** [comment]
issue number #104

**Comment by PrachiChauhan23** [comment]
sir i have cloned this repository many times to resolve the conflict after deleting all the files from my laptop. But everytime i m getting this issue. @codervivek5

**Comment by codervivek5** [comment]
kindly solve it then I will merge it.

**Comment by PrachiChauhan23** [comment]
sir i don't know how to do it . everytime i resolve it . someone else do other changes and it got conflicts. please help me out.

**Comment by PrachiChauhan23** [comment]
i resolved it sir @codervivek5 .Please merge this. otherwise it will get another conflict.

**Comment by JigarJoshi04** [comment]
> sir i have cloned this repository many times to resolve the conflict after deleting all the files from my laptop. But everytime i m getting this issue. @codervivek5

For resolving merge conflict you don't have to do this.
I understand that merge conflict resolution is a tricky and irritating thing.
Let's connect over a call and we can collaborate on this PR.
Works?

**Comment by JigarJoshi04** [comment]
> Screenshot 2023-05-24 103204

Also IDK why this screenshot is shared.
But by @codervivek5 comment, I think he asked you to share the final changes as someone reviewing can understannd the working status.

**Comment by PrachiChauhan23** [comment]
> > Screenshot 2023-05-24 103204
> 
> Also IDK why this screenshot is shared. But by @codervivek5 comment, I think he asked you to share the final changes as someone reviewing can understannd the working status.

Yes . He told  me to share the screenshot.

**Review by JigarJoshi04 — APPROVED** [review]
LGTM if tested.
For merge conflict let's sit together on discord to resolve it.

**Comment by JigarJoshi04** [comment]
> > > Screenshot 2023-05-24 103204
> > 
> > 
> > Also IDK why this screenshot is shared. But by @codervivek5 comment, I think he asked you to share the final changes as someone reviewing can understannd the working status.
> 
> Yes . He told me to share the screenshot.

Could you please share the link of diff?
Is this the screenshot of the file changed?
If so, I guess this file is missing from the PR.

**Comment by JigarJoshi04** [comment]
This has been completed via other PRs.
After discussion with author, I'm closing this PR.

**Pull request closed without merging**
