### PR TITLE
text animation added

### LINKED ISSUE #1494: text animation on first page
https://github.com/codervivek5/VigyBag/assets/95361125/ecbe2e7f-44ab-42dc-a56e-8731c8ffbac3

Add a text animation on the first page where the main heading smoothly fades in and slides up from the bottom. This effect grabs the visitor's attention and provides a dynamic entry experience.

### PR DESCRIPTION
**Pull request by heli0707**
close issue: #1494 

## Fixes Issue 
simple text animations can enhance the visual appeal of a website more effectively than overloading the entire page with complex animations.

add animation on the text of the first page.

## Video

https://github.com/codervivek5/VigyBag/assets/95361125/cd214266-2b07-4c2d-ad86-893fd7ca86d6

close #1494 

## Summary by CodeRabbit

- **New Features**
	- Enhanced welcome message with animated text split into left and right sections.
	- Added new animations and delays to text elements for a more dynamic user experience.

- **Styling Changes**
	- Updated paragraph styling with fade-in animations.
	- Enhanced button styling with 3D fade-in animations and delays for improved interactivity.

These changes aim to make the homepage more engaging and visually appealing.

### CODE REVIEW

**Comment by heli0707** [comment]
@codervivek5 please review PR and merge it!

**Comment by codervivek5** [comment]
Kindly solve merge conflict

**Comment by heli0707** [comment]
@codervivek5 conflict resolved 
review and merge it

**Comment by heli0707** [comment]
@codervivek5 
review and close it

**Comment by heli0707** [comment]
@codervivek5 conflict resolved
review and merge it!

**Comment by codervivek5** [comment]
no need of this feature

**Pull request closed without merging**
