### PR TITLE
Added "Scroll-to-Top" Button to new VigyBag Website

### LINKED ISSUE #1540: Feature Addition: Scroll-to-Top Button to new VigyBag Website
Hey @codervivek5 

I've noticed that the VigyBag website currently lacks a **scroll-to-top button**, which can enhance user experience, especially on longer pages.

- Adding a scroll-to-top button would allow users to easily navigate back to the top of the page with a single click. 
- This feature is particularly useful on pages with extensive content, improving accessibility and user navigation

Could you please assign this issue to me?

### PR DESCRIPTION
**Pull request by MastanSayyad**
## Fixes Issue

Issue closes #1540 

## Changes proposed

Hey @codervivek5  I have added the scroll to top button the website
- Implemented a `GoToTop` component using React and `styled-components.`
- Added a button that appears when the user scrolls down `isVisible state`.
- Background color in base `#16a34a` | On Hover `#005a01`
- Added a smooth hover effect and smooth animation

## Screenshots

https://github.com/codervivek5/VigyBag/assets/101971980/7a7befce-3272-4b92-bab9-d88649737faf

## Summary by CodeRabbit

- **New Features**
  - Introduced a "Go to Top" button that allows users to easily scroll back to the top of the page. The button appears based on the user's scroll position and features a smooth scrolling animation.
- **Dependencies**
  - Added `styled-components` to the project dependencies for styling the new "Go to Top" button component.

### CODE REVIEW

**Comment by codervivek5** [comment]
debug this code ... vercel deployment failed so if I merged your PR then the change will not reflected kindly solve these

Error:

[03:47:27.916] Running build in Washington, D.C., USA (East) – iad1
[03:47:29.526] Cloning github.com/codervivek5/VigyBag (Branch: main, Commit: 0a27834)
[03:47:35.586] Cloning completed: 6.058s
[03:47:36.242] Restored build cache
[03:47:36.387] Running "vercel build"
[03:47:37.496] Vercel CLI 34.2.8
[03:47:39.209] Installing dependencies...
[03:47:42.952] 
[03:47:42.953] up to date in 2s
[03:47:42.954] 
[03:47:42.954] 126 packages are looking for funding
[03:47:42.954]   run `npm fund` for details
[03:47:42.985] Detected `package-lock.json` generated by npm 7+
[03:47:42.986] Running "npm run build"
[03:47:43.580] 
[03:47:43.580] > vigybag@0.0.0 build
[03:47:43.581] > vite build
[03:47:43.581] 
[03:47:44.498] [36mvite v5.3.2 [32mbuilding for production...[36m[39m
[03:47:44.612] transforming...
[03:47:48.650] [32m✓[39m 72 modules transformed.
[03:47:48.656] [31mx[39m Build failed in 4.10s
[03:47:48.661] [31merror during build:
[03:47:48.661] [31m[vite]: Rollup failed to resolve import "styled-components" from "/vercel/path0/src/components/gototop.jsx".
[03:47:48.662] This is most likely unintended because it can break your application at runtime.
[03:47:48.662] If you do want to externalize this module explicitly add it to
[03:47:48.662] `build.rollupOptions.external`[31m
[03:47:48.662]     at viteWarn (file:///vercel/path0/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:65876:17)
[03:47:48.662]     at onwarn (file:///vercel/path0/node_modules/@vitejs/plugin-react/dist/index.mjs:266:9)
[03:47:48.662]     at onRollupWarning (file:///vercel/path0/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:65909:5)
[03:47:48.662]     at onwarn (file:///vercel/path0/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:65571:7)
[03:47:48.662]     at file:///vercel/path0/node_modules/rollup/dist/es/shared/node-entry.js:18514:13
[03:47:48.662]     at Object.logger [as onLog] (file:///vercel/path0/node_modules/rollup/dist/es/shared/node-entry.js:20162:9)
[03:47:48.662]     at ModuleLoader.handleInvalidResolvedId (file:///vercel/path0/node_modules/rollup/dist/es/shared/node-entry.js:19104:26)
[03:47:48.662]     at file:///vercel/path0/node_modules/rollup/dist/es/shared/node-entry.js:19062:26[39m
[03:47:48.696] Error: Command "npm run build" exited with 1
[03:47:49.535]

**Comment by codervivek5** [comment]
check this GPT responce:
https://chatgpt.com/share/5fd11907-26cf-4d10-9da8-6220ad837ed2

**Comment by codervivek5** [comment]
do not build the project this process internally work only check the dependency issues

**Comment by MastanSayyad** [comment]
Done @codervivek5, thanks for letting me know!

**Comment by codervivek5** [comment]
Is this design responsive?

**Comment by MastanSayyad** [comment]
> Is this design responsive?

Yes @codervivek5 


https://github.com/codervivek5/VigyBag/assets/101971980/6ea9cc2e-1cbe-4d43-93fe-d166718eb340

**Review by codervivek5 — APPROVED** [review]

**Pull request merged**
