### PR TITLE
Added Animated icon to the Navbar links

### LINKED ISSUE #1094: features :  Adding Animated icons in the Navbar links
these Animated icon will give more good look to the page

### PR DESCRIPTION
**Pull request by SadafKausar2025**
## Screenshots

https://github.com/codervivek5/VigyBag/assets/137484958/3ed251d1-b1de-44fc-b674-61d19f6fbc25

## Note to reviewers

Please label it by Gssoc '24

### CODE REVIEW

**Comment by SadafKausar2025** [comment]
https://github.com/codervivek5/VigyBag/assets/137484958/48a47428-9d58-4ec8-9f0c-e5bcc841c0f4

**Comment by SadafKausar2025** [comment]
hi @codervivek5 

I have added more animated icons which beautify the projects

**Comment by SadafKausar2025** [comment]
Can you please assign me ?
and merge this PR

**Comment by codervivek5** [comment]
Sorry I was busy so I can't see any new updates but now I can

you work amazingly. I suggest you kindly join VigyBag discord if in the future I need any candidate like you then definitely i will ping you

Thankyou for your contribution :)

**Comment by SadafKausar2025** [comment]
Thank You 
It's Ok

**Pull request merged**
