### PR TITLE
fixed container in the home page

### PR DESCRIPTION
**Pull request by SyedImtiyaz-1**
Hello @codervivek5 ,

Issue fixed regarding the home page issue of container.

# Screenshot - 
Screenshot from 2023-05-26 17-57-56

### CODE REVIEW

**Comment by codervivek5** [comment]
Kindly solve merge conflict

**Comment by SyedImtiyaz-1** [comment]
@codervivek5 ,
Conflicts resolved!

**Comment by codervivek5** [comment]
Try to mention issue number in each PR
Kindly choose the issue after CLOSE this PR

**Comment by SyedImtiyaz-1** [comment]
@codervivek5  Thank you !
I will remember next time.

**Pull request merged**
