### PR TITLE
Footer fixed #1829

### LINKED ISSUE #1829: Footer overflows in vertical direction
There is white line at the end of footer which appears , kindly aassign to me i can fix that, it looks unappealing and ruins look of whole website when scorlled down enough
Screenshot 2024-07-15 221314

### PR DESCRIPTION
**Pull request by Priyal208**
## Fixes Issue
Fixes #1829 

Close #1829

## Changes proposed
The footer overflowed vertically I adjust and translated footer and above components appropriated so that white space at bottom is eliminated , as well as made sure that it responsive also

## Screenshots

https://github.com/user-attachments/assets/01a5e19b-4469-436f-94cc-e4ec2f3f53d1

## Note to reviewers
You can see in the video the extra white space is eliminated and no further scroll to white bottom happens

## Summary by CodeRabbit

- **Style**
  - Updated footer positioning to have a slight vertical translation for improved layout alignment on the page.
- **Refactor**
  - Adjusted home page component styling for consistent vertical translation matching the footer adjustment.

### CODE REVIEW

**Comment by Priyal208** [comment]
@codervivek5 kindly review this

**Comment by Priyal208** [comment]
@codervivek5 pls review

**Comment by codervivek5** [comment]
kindly solve merge conflict

**Comment by Priyal208** [comment]
@codervivek5 
This branch has conflicts that must be resolved
Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.
Conflicting files
src/components/Footer/Footer.css
src/pages/Home/Home.jsx

I cant see the files where exactly conflict is happening  , this is the problem

**Review by codervivek5 — APPROVED** [review]

**Comment by codervivek5** [comment]
Your PR is approved.Kindly solve conflict then I'll merge it

**Comment by Priyal208** [comment]
Still , I dont have access, Also I have two other PRs with no conflicts kindly merge them pls
Screenshot 2024-07-20 223118
@codervivek5 pls merge other PRs

**Comment by Priyal208** [comment]
@codervivek5 pls look into this and my other 2 PRs also asap pls

**Comment by codervivek5** [comment]
Join meet when You will be free..et me know the timing

**Comment by Priyal208** [comment]
@codervivek5 at 9:30 pm today?

**Comment by Priyal208** [comment]
I created al-together new PR with the same changes pulling latest code without conflicts , #1945
Kindly review that and also my other 2 PRs that havr no conflicts @codervivek5

**Pull request closed without merging**
