### PR TITLE
fixed about us brand logo link

### LINKED ISSUE #703: About us page brand logo link in not working
image

### PR DESCRIPTION
**Pull request by krutikajichkar**
fixed #703 
Closes #703 

https://github.com/codervivek5/VigyBag/assets/93243210/ee02d941-20c5-4c90-890b-0969ef17cdf9

### CODE REVIEW

**Comment by krutikajichkar** [comment]
@codervivek5 please review my PR

**Comment by codervivek5** [comment]
kindly solve merge conflict

**Comment by krutikajichkar** [comment]
@codervivek5 conflicts have been solved , kindly review the PR

**Comment by codervivek5** [comment]
kindly solve conflict then i will merge it

**Comment by krutikajichkar** [comment]
@codervivek5 check now

**Pull request merged**
