### PR TITLE
Fix size and overflow

### LINKED ISSUE #853: Fix size and overflow
Screenshot 2023-09-26 at 1 06 17 PM

- Reduced size of each product 
- also fix overflow of product 
- try to add a Slider button for the overflow product

### PR DESCRIPTION
**Pull request by Tanush-J**
## Fixes Issue
Closes #853

## Changes proposed
I have reduced the space between different cards and added scroll functionality using buttons in all 3 (i.e Headphones for you, T-shirts for you and Mobiles for you) section.

## Screenshots
image

https://github.com/codervivek5/VigyBag/assets/75922615/c6641019-e5ca-4ff1-bc64-8ca66d87c15f

## Note to reviewers

If you have any more recommendations do tell me.

### CODE REVIEW

**Comment by codervivek5** [comment]
make scroll product 4x4 means when user click then 4 product slide at once and also check that it is responsive or not

**Comment by Tanush-J** [comment]
I have added 4 card scrolls, resized the cards, and made the image and card responsive. 

https://github.com/codervivek5/VigyBag/assets/75922615/03d8397d-6daf-4ab6-9ce1-2549f3ad15a1

**Comment by codervivek5** [comment]
Thanks for your contributions.
can I merge it now ?

**Comment by Tanush-J** [comment]
Can I create a new pull request with same code, coz I don't know if this will count for hactoberfest.

**Comment by codervivek5** [comment]
> Can I create a new pull request with same code, coz I don't know if this will count for hactoberfest.

no need for it I will merge it and will count :)

**Review by codervivek5 — APPROVED** [review]

**Comment by codervivek5** [comment]
Thankyou for your contribution :)

**Comment by Tanush-J** [comment]
This PR didn't count towards hackoberfest :confused:

**Pull request merged**
