### PR TITLE
fixed logo and added styles to about page

### LINKED ISSUE #622: Brand logo is not visible
Brand logo is not visible due to path given to the image , i want fix that , please assign me this under gssoc'23

Screenshot (172)

### PR DESCRIPTION
**Pull request by krutikajichkar**
fixed #622 

IS this UI Ok or you need some changes?
Screenshot (176)

### CODE REVIEW

**Comment by krutikajichkar** [comment]
about page is made responsive as well

**Comment by codervivek5** [comment]
shift about us to the left align to img 
- add a button below to the text "see more" then make PR
everything  is perfect 👍

**Comment by krutikajichkar** [comment]
Screenshot (182)

@codervivek5 please review these changes

**Comment by codervivek5** [comment]
kindly share your anyout put after make changeq

**Comment by krutikajichkar** [comment]
> Screenshot (182)
> 
> @codervivek5 please review these changes

@codervivek5  here is the output

**Comment by krutikajichkar** [comment]
Screenshot (183)

responsive

**Comment by codervivek5** [comment]
@krutikajichkar is it possible to make some more changes ?
image
add this content so that I will look like a about us page...


I will increase the level after finish this task.if you can add it then plz let me know

**Comment by codervivek5** [comment]
- you can get this test content from README file 
- if it is possible to remove "about us" from image then plz remove and if not possible then remove the  heading "about us"

**Comment by krutikajichkar** [comment]
okay @codervivek5 i will do that

**Comment by krutikajichkar** [comment]
Screenshot (184)

@codervivek5  please have a look , if this ok ,then i will make PR

**Comment by codervivek5** [comment]
Ohhhhoooooo @krutikajichkar heading always use upper then paragraph kindly ups heading

so if you are .....................................................this line

**Comment by krutikajichkar** [comment]
@codervivek5

**Comment by krutikajichkar** [comment]
Screenshot (185)

@codervivek5

**Comment by codervivek5** [comment]
is this page link to the home page...
please check it once

**Comment by krutikajichkar** [comment]
Actually the whole linkage has broken , on contact page , on about page everywhere , i have raised another issue for that , i am linking this to home for now @codervivek5

**Comment by codervivek5** [comment]
> Actually the whole linkage has broken , on contact page , on about page everywhere , i have raised another issue for that , i am linking this to home for now @codervivek5

ok but wait fo some time because I think someone is working on it....you can raised a issue and share the link with e in discord or anywhere I will assign it to you tomorrow at evening

**Comment by codervivek5** [comment]
you deserve Leve2 instead of Level1 👍

**Comment by krutikajichkar** [comment]
I have linked it to home and contact @codervivek5

**Pull request merged**
