### PR TITLE
Issue #942 ,Responsiveness

### PR DESCRIPTION
**Pull request by jayraj175coder**

### CODE REVIEW

**Comment by codervivek5** [comment]
share your changes so that i can review

**Comment by jayraj175coder** [comment]
Hi @codervivek5 , This are the changes I did in styling:

/* Media queries for small devices */
@media screen and (max-width: 767px) {
  .container {
    flex-direction: column;
    align-items: center;
    padding-top: 20px;
  }
  .container img {
    width: 100%;
    max-width: 40px;
    height: auto;
    margin: 2px 40px;
  }
 
  .container a {
    font-size: 16px;
  }

  .content {
    text-align: center;
    padding: 0 20px;
  }

  .content h1 {
    font-size: 40px;
  }

  .content h4 {
    font-size: 16px;
    margin-top: 20px;
    padding-right: 20px;
  }

 

  .local input[type='search'] {
    padding: 10px 20px;
    font-size: 18px;
  }

  .Accessories-box {
    width: 100%;
    margin: 20px 0;
  }

  .rectangle-42 {
    height: 150px;
  }

  .product-name {
    font-size: 18px;
  }
  .container .sec-img{
    max-width: 1000px;
    }
}

/* Media queries for larger mobile devices and tablets */
@media screen and (min-width: 768px) and (max-width: 991px) {
  .content h1 {
    font-size: 60px;
  }

  .content h4 {
    font-size: 18px;
  }
  .container img {
    width: 100%;
    max-width: 70px;
    height: auto;
    margin: 20px 0;
  }
 .container .sec-img{
  max-width: 1000px;
  }
  
}



/* Media queries for tablets and smaller laptops */
@media screen and (min-width: 992px) and (max-width: 1199px) {
  .content h1 {
    font-size: 70px;
  }

  .content h4 {
    font-size: 20px;
  }
  .container img {
    width: 100%; 
    max-width: 70px; 
    height: auto; 
    margin: 20px 0; 
  }
  .container .sec-img{
    max-width: 1000px;
  }
}

**Comment by codervivek5** [comment]
bro share screens shot

**Comment by jayraj175coder** [comment]
See @codervivek5  Screenshots,
Screenshot 2024-05-11 090455
Screenshot 2024-05-11 090519
Screenshot 2024-05-11 090537
Screenshot 2024-05-11 090546
Screenshot 2024-05-11 090557

**Comment by codervivek5** [comment]
kindly mention your issue number

**Comment by jayraj175coder** [comment]
Hi, My issue number is #942 

Not responsive for mobile devices, I want to make it responsive #942

**Comment by codervivek5** [comment]
ok got it but you need to make some more changes like FAQ section is perfect
- reduced the size of the Google button and mobile and set them side by side only for mobile devices 
- reduced the image size of "**our services**"
- also fix the product size like headphones and t-shirts size

**Comment by jayraj175coder** [comment]
HI @codervivek5 I did changes as per your wish,
My issue no is #942 ..
Screenshot 2024-05-11 145130

Screenshot 2024-05-11 145136

Screenshot 2024-05-11 145115

**Comment by codervivek5** [comment]
image
 headphone section in not fixed see the price tag is overflow to other

**Comment by jayraj175coder** [comment]
Done @codervivek5 , See this : 
Screenshot 2024-05-12 100000
Issue #942.

**Comment by codervivek5** [comment]
ok now perfect

**Comment by jayraj175coder** [comment]
Hi @codervivek5 , 
I have one request for you plz change my label to level3 it only count level wise.
See this.
Screenshot_2024-05-12-14-53-58-937_com discord

**Comment by codervivek5** [comment]
Thankyou for let me know about this

**Pull request merged**
