### PR TITLE
added hover effect to product cards

### PR DESCRIPTION
**Pull request by Amarjit0511**
Added hover effect#102
Screenshot 2023-05-22 at 10 54 48 AM

### CODE REVIEW

**Comment by codervivek5** [comment]
kindly show me your changes so that I can review

**Comment by Amarjit0511** [comment]
Screenshot 2023-05-22 at 11 29 16 AM

**Comment by Amarjit0511** [comment]
After these changes, i ran it locally to see if it worked fine. And upon checking, the hover effect was working fine with the product cards.

**Comment by codervivek5** [comment]
kindly solve merge conflict

**Pull request closed without merging**
