### PR TITLE
Added auto-comment.yml file

### PR DESCRIPTION
**Pull request by DivyanshiNarang**
Closes issue #390 

Addition of auto-comment file to provide necessary information to the contributors when they create new issues, PR, and when these will get assigned or merged respectively.

@codervivek5 Please review this PR.

### CODE REVIEW

**Comment by DivyanshiNarang** [comment]
@codervivek5 please add gssoc23 and level label to this PR.

**Comment by codervivek5** [comment]
> @codervivek5 please add gssoc23 and level label to this PR.

sure

**Comment by codervivek5** [comment]
@DivyanshiNarang can you fix this for java in      "  .yml file  ".

there is separate file but I don't know that name

image

**Comment by DivyanshiNarang** [comment]
Hello @codervivek5 , Please enable these permissions in order to make this workflow work as expected.
Screenshot 2023-07-16 210427

**Pull request merged**
