### PR TITLE
Implemented reCAPTCHA

### LINKED ISSUE #1027: [Feat]: reCAPTCHA Implementation
**Description:**

Implementing reCAPTCHA on the VigyBag website will help in enhancing security, preventing spam and unauthorized access, protecting user data.
This also helps in preventing automated bots from accessing or submitting forms on the website.

**Solution:** 

I would consider using reCAPTCHA v3, which provides a more user-friendly way to detect bots without requiring any interaction from the user.
I will prefer integrating reCAPTCHA in signup page as it will help prevent bot registrations on the site.

### PR DESCRIPTION
**Pull request by antriksh-9**
## Fixes Issue

Closes #1027.

## Screenshots

Screenshot 2024-05-15 130936
Screenshot 2024-05-15 130950

### CODE REVIEW

**Comment by codervivek5** [comment]
image
 kindly fix the recapta place it is taking other place also

**Comment by antriksh-9** [comment]
Hey @codervivek5 actually that is due to default hover effect on the captcha badge provided by google which can't be changed. 
Although, I tried changing the position of the reCAPTCHA badge, but it moves only up & down in the container.
It's default position is at the bottom right of the screen but here in our case the badge is being constrained by a parent container.
So, the solution is we can keep this as it is as the badge do not obstruct any element when not hovered or we can completely hide the captcha badge.
Which should you want to consider, I will make changes according to that.

**Comment by BTANISHA11** [comment]
@antriksh-9 we can't hide it but we can adjust form buttons accordingly if you can do it.

**Comment by antriksh-9** [comment]
Hey @BTANISHA11, Is this fine?

Screenshot 2024-05-18 113014

Screenshot 2024-05-18 113252

**Comment by BTANISHA11** [comment]
> Hey @BTANISHA11, Is this fine?
> 
> Screenshot 2024-05-18 113014
> 
> Screenshot 2024-05-18 113252

@codervivek5 will this work?

**Comment by codervivek5** [comment]
> > Hey @BTANISHA11, Is this fine?
> > Screenshot 2024-05-18 113014
> > Screenshot 2024-05-18 113252
> 
> @codervivek5 will this work?

img is not showing

**Comment by codervivek5** [comment]
@BTANISHA11 if you review it finally then approve it and if possible then merge it with proper label - gssoc, level, good-first-issue

**Comment by antriksh-9** [comment]
Hey @codervivek5 @BTANISHA11, please assign necessary `level` label to my PR.

**Comment by BTANISHA11** [comment]
> Hey @codervivek5 @BTANISHA11, please assign necessary `level` label to my PR.

it's done @antriksh-9

**Pull request merged**
