### PR TITLE
Added Buy Now Button with Animated icon

### LINKED ISSUE #1136: FEATURE: Adding new (Buy Now) Buttons in every products.
It will be very good to add this Buy Now button in the product so that if someone wants to buy only one product then it will be easy

https://github.com/codervivek5/VigyBag/assets/137484958/0cfccbac-d20c-4ce9-a079-bd30a1b4a0a1

### PR DESCRIPTION
**Pull request by SadafKausar2025**
## Fixes Issue #1136

It will be very good to add this Buy Now button in the product so that if someone wants to buy only one product then it will be easy

https://github.com/codervivek5/VigyBag/assets/137484958/0cfccbac-d20c-4ce9-a079-bd30a1b4a0a1

### CODE REVIEW

**Comment by SadafKausar2025** [comment]
hi @codervivek5 

can you please merge this PR?

**Comment by codervivek5** [comment]
Thankyou for your Contribution :)

**Comment by SadafKausar2025** [comment]
Please also label it

**Comment by BTANISHA11** [comment]
Good work @SadafKausar2025

**Pull request merged**
