### PR TITLE
ProductCare Page is Added

### LINKED ISSUE #2051: Product Care page is Added
Product Care page is Added

### PR DESCRIPTION
**Pull request by Tanmay-Mirgal**
## Fixes Issue

Fix Issue : #2051
Closes: #2051

## Summary by CodeRabbit

- **New Features**
  - Reintroduced routes for Sponsorships, Warranty, Product Care, and Subscription pages, enhancing navigation options.
  - Added a dedicated Product Care page featuring essential maintenance and cleaning guidelines, improving user experience and satisfaction.

- **Style**
  - Enhanced visual appeal of the Product Care page using Tailwind CSS and smooth transition effects with the motion library. 

- **Bug Fixes**
  - Cleaned up the routing code by removing unnecessary whitespace and commented-out snippets for better readability.

### CODE REVIEW

**Comment by codervivek5** [comment]
check error

**Comment by codervivek5** [comment]
[13:05:32.120] Running build in Washington, D.C., USA (East) – iad1
[13:05:32.339] Cloning github.com/codervivek5/VigyBag (Branch: care, Commit: 027f88e)
[13:05:43.164] Cloning completed: 10.822s
[13:05:43.879] Restored build cache
[13:05:43.966] Running "vercel build"
[13:05:44.420] Vercel CLI 35.2.1
[13:05:45.386] Installing dependencies...
[13:05:48.275] 
[13:05:48.276] up to date in 3s
[13:05:48.276] 
[13:05:48.276] 174 packages are looking for funding
[13:05:48.277]   run `npm fund` for details
[13:05:48.294] Detected `package-lock.json` generated by npm 7+
[13:05:48.294] Running "npm run build"
[13:05:48.427] 
[13:05:48.427] > vigybag@0.0.0 build
[13:05:48.427] > vite build
[13:05:48.428] 
[13:05:48.722] [36mvite v5.3.5 [32mbuilding for production...[36m[39m
[13:05:48.778] transforming...
[13:05:49.071] [32m✓[39m 4 modules transformed.
[13:05:49.072] [31mx[39m Build failed in 320ms
[13:05:49.073] [31merror during build:
[13:05:49.073] [31m[vite:esbuild] Transform failed with 1 error:
[13:05:49.073] /vercel/path0/src/App.jsx:229:12: ERROR: Expected ">" but found "<"[31m
[13:05:49.073] file: [36m/vercel/path0/src/App.jsx:229:12[31m
[13:05:49.073] [33m
[13:05:49.073] [33mExpected ">" but found "<"[33m
[13:05:49.074] 227|              <Route path="blog" element={<Blog />}
[13:05:49.074] 228|              //additional routes
[13:05:49.074] 229|              <Route path="giftcard" element={<GiftcardPage />} />
[13:05:49.079]    |              ^
[13:05:49.079] 230|              <Route path="sponsorships" element={<Sponsorships />} />
[13:05:49.079] 231|              <Route path="warranty" element={<Warranty/>} />
[13:05:49.079] [31m
[13:05:49.079]     at failureErrorWithLog (/vercel/path0/node_modules/esbuild/lib/main.js:1472:15)
[13:05:49.079]     at /vercel/path0/node_modules/esbuild/lib/main.js:755:50
[13:05:49.080]     at responseCallbacks.<computed> (/vercel/path0/node_modules/esbuild/lib/main.js:622:9)
[13:05:49.080]     at handleIncomingPacket (/vercel/path0/node_modules/esbuild/lib/main.js:677:12)
[13:05:49.080]     at Socket.readFromStdout (/vercel/path0/node_modules/esbuild/lib/main.js:600:7)
[13:05:49.080]     at Socket.emit (node:events:520:28)
[13:05:49.080]     at addChunk (node:internal/streams/readable:559:12)
[13:05:49.080]     at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
[13:05:49.080]     at Readable.push (node:internal/streams/readable:390:5)
[13:05:49.080]     at Pipe.onStreamRead (node:internal/stream_base_commons:191:23)[39m
[13:05:49.101] Error: Command "npm run build" exited with 1
[13:05:49.544]

**Comment by Tanmay-Mirgal** [comment]
done

**Comment by Tanmay-Mirgal** [comment]
/> was missing in blog route

**Review by codervivek5 — APPROVED** [review]

**Comment by sanjay-kv** [comment]
@codervivek5 I need access to this repo, requested multiple times else might have to block the repo.

**Comment by codervivek5** [comment]
> @codervivek5 I need access to this repo, requested multiple times else might have to block the repo.

This is the first time, I got your message for repo access.


Ok I'll

**Comment by codervivek5** [comment]
@sanjay-kv kindly let me know if you find any issue like spam

**Pull request merged**
