### PR TITLE
applied the dark mode button

### PR DESCRIPTION
**Pull request by parasss19**
## Description 
Successfully  applied the dark mode button on home page and its working properly

## ScreenShot

https://github.com/codervivek5/VigyBag/assets/101205226/1261066d-b012-4ed0-9670-f2195086af13

### CODE REVIEW

**Comment by parasss19** [comment]
## Hi @codervivek5  I resolved the issue #282 
## Please review it once

**Comment by codervivek5** [comment]
Could you make some changes?
 first of all, pull the code, and reduce the size of the dark mode button.  and shift it little bit right.

Remember, do not remove others' code if not necessary for you.

**Comment by parasss19** [comment]
> Could you make some changes? first of all, pull the code, and reduce the size of the dark mode button. and shift it little bit right.
> 
> Remember, do not remove others' code if not necessary for you.

Hi @codervivek5 
- Pull the changes 
- Decreased the width of dark mode button
- Shift the button to right

**Comment by codervivek5** [comment]
let me check it once
send me your output.after the review I will merge your PR

**Comment by parasss19** [comment]
> let me check it once send me your output.after the review I will merge your PR


https://github.com/codervivek5/VigyBag/assets/101205226/4945a4dd-9b56-46e5-b792-aee75f3450fe

**Comment by parasss19** [comment]
Hi @codervivek5 review it once and add the level label pls

**Pull request closed without merging**
