### PR TITLE
now website is not broken issue solved

### PR DESCRIPTION
**Pull request by Sushilverma002**
@codervivek5 have alook!!!!!!!!
close issue -> #641

### CODE REVIEW

**Comment by Sushilverma002** [comment]
https://github.com/codervivek5/VigyBag/assets/114687502/455cdeca-ff8f-412a-9510-b61003bae587

**Comment by codervivek5** [comment]
bro if the footer is also fixed then kindly share any output...if there will be any changes then I will suggest you

**Comment by Sushilverma002** [comment]
image

**Comment by Sushilverma002** [comment]
here it is have a look

**Comment by Sushilverma002** [comment]
https://github.com/codervivek5/VigyBag/assets/114687502/cfe438aa-b7e3-4d1e-94cc-aa03299d056c

a full video now it will help you @codervivek5

**Comment by Sushilverma002** [comment]
thank you @codervivek5 👍

**Comment by codervivek5** [comment]
@Sushilverma002  can you remove buttom scroll bar ??

**Comment by codervivek5** [comment]
and can you make complete home page responsive?

**Comment by Sushilverma002** [comment]
> @Sushilverma002 can you remove buttom scroll bar ??

which one ?

**Comment by codervivek5** [comment]
image
this one look ate the buttom scroll bar

**Comment by Sushilverma002** [comment]
image
image
just tell me one this the why the content on every single product is same?

**Comment by Sushilverma002** [comment]
> image this one look ate the buttom scroll bar

ok i will do.

**Comment by Sushilverma002** [comment]
i will make PR ASAP.

**Comment by codervivek5** [comment]
this is hardcoded that is the reason the content is the same.........we will manipulate it from the backend code

**Comment by codervivek5** [comment]
> i will make PR ASAP.

bro try to make only the homepage mobile and tablet responsive so that it can also open in mobile
- also raise a separate issue so that you can get your points

**Comment by Sushilverma002** [comment]
OK GOT IT... I WILL MAKE IT responsive.

**Comment by Sushilverma002** [comment]
> > i will make PR ASAP.
> 
> bro try to make only the homepage mobile and tablet responsive so that it can also open in mobile
> 
> * also raise a separate issue so that you can get your points

for sure

**Pull request merged**
