### PR TITLE
dark mode color updated

### LINKED ISSUE #775: dark mode does not work
in dark mode text navbar and many more things are not visible 
image
image

in contact us dark mode is not available 

image

### PR DESCRIPTION
**Pull request by RitiChandak**
##775

 Closes #775 

## Screenshots

image
image
image

### CODE REVIEW

**Comment by RitiChandak** [comment]
@codervivek5 please review this pr

**Comment by codervivek5** [comment]
why you change the color...it is not seem like dark mode

**Comment by codervivek5** [comment]
try this website 
https://mdigi.tools/darken-color/#008000

**Comment by RitiChandak** [comment]
As soon as you change the website to dark mode in card the color of text also changes to white due to which the content of card is not visible

**Comment by codervivek5** [comment]
> As soon as you change the website to dark mode in card the color of text also changes to white due to which the content of card is not visible

but it is not look like dark mode ....?

**Comment by RitiChandak** [comment]
Which image you are referring to

**Comment by RitiChandak** [comment]
1st image refer to this is how it looks in dark mode 
2nd image is to show that changes are only made in dark mode and the change does not affect light mode

**Comment by RitiChandak** [comment]
image

This is the recent image of the website

**Comment by codervivek5** [comment]
> 1st image refer to this is how it looks in dark mode 2nd image is to show that changes are only made in dark mode and the change does not affect light mode

ohhhhh .....i was thinking that you change in second img 🤣😂

**Comment by codervivek5** [comment]
wait I am merging your PR

**Comment by RitiChandak** [comment]
No problem 😂

**Pull request merged**
