### PR TITLE
Fixed issue #1067 

### PR DESCRIPTION
**Pull request by Anuja1227**

### CODE REVIEW

**Review by codervivek5 — APPROVED** [review]

**Comment by codervivek5** [comment]
Thankyou for your Contribution :)

**Comment by Anuja1227** [comment]
Editable figma file : https://www.figma.com/design/MUG5F222vCZo90U8AiZ5q9/All-Logos?node-id=0%3A1&t=UlNWlOsUPcPnXeiA-1

**Comment by codervivek5** [comment]
Kindly close the issue related to this  PR

**Comment by Anuja1227** [comment]
> Thankyou for your Contribution :)

My Pleasure...

**Pull request merged**
