### PR TITLE
improve ui in filters

### LINKED ISSUE #1851: Improve UI of filters
The filter section drop down menu looks very plain and simple white and blue, I can improve the UI and make it more beuatiful and appealing and colorful as per website theme, kindly assign this to me under gssoc
Screenshot 2024-07-16 153811

### PR DESCRIPTION
**Pull request by Priyal208**
#1851  fixed
Close #1851

## Changes proposed

I improved UI of filters section, changed colors also changed them specifically for hover and focus, as you can see in the below image , on hover there is different color and when one section is focused i.e open color changes, I also give some curvature to the rectangular div to make it look more appealing

Thus i made the UI better beautiful and more attractive

## Screenshots
Screenshot 2024-07-17 225656
Screenshot 2024-07-17 225705

## Summary by CodeRabbit

- **Style**
  - Improved the visual design and interactivity of the filter section in the Popular Categories component, including updates to the select element and option elements for a more engaging user experience.

### CODE REVIEW

**Comment by Priyal208** [comment]
@codervivek5 pls review this

**Comment by Priyal208** [comment]
@codervivek5 pls review

**Comment by codervivek5** [comment]
make is same color not like multi color

**Comment by Priyal208** [comment]
@codervivek5 i dont understand what youre saying, pls specify further

**Comment by Priyal208** [comment]
@codervivek5 pls merge this

**Comment by codervivek5** [comment]
there is no need to make any changes to this dashboard page...if needed then I'll raise a new issue

**Comment by codervivek5** [comment]
actually filter is not in the right place or not seem like working correct..... there is some bugs in filter so at this time we can't add your PR for these changes.

you can find another issue then let me know if that will needful then definetly assgin to you

I can understand of your effort but sorry for now.

**Pull request closed without merging**
