### PR TITLE
new feature for chatbot

### PR DESCRIPTION
**Pull request by krishvsoni**

### CODE REVIEW

**Comment by krishvsoni** [comment]
please check  script.js in chatbot

**Comment by krishvsoni** [comment]
Update script.js
Clear Chat History:

I added a "Clear Chat History" button with the class chatbox-clear-history.
When clicked, it clears the chatbox message content by setting the innerHTML of chatboxMessageWrapper to an empty string.
Additionally, it displays the "No Messages" text by setting the display property of chatboxNoMessage to 'block'.
Dark Mode Toggle:

I added a dark mode toggle button with the class chatbox-toggle-dark-mode.
However, the implementation of dark mode functionality is not included in the provided code snippet. It is only the button itself.

**Review by codervivek5 — APPROVED** [review]

**Comment by codervivek5** [comment]
kindly mention close the issue related to this PR so that you can get your point.

**Comment by codervivek5** [comment]
image
There is no button reflected for the clear chat history and other feature also does not reflect.

**Comment by codervivek5** [comment]
check it once because chatbot it not opening now

**Pull request merged**
