### PR TITLE
Contact Us page added

### LINKED ISSUE #349: Create a separate Contact Us Page with the website design
Clicking on the Contact us doesn't navigate to anywhere. I would like to create a separate Contact Us page for users to interact

image

### PR DESCRIPTION
**Pull request by PoulavBhowmick03**
Added Contact Us Page and linked it to navbar
 Close #349 

https://github.com/codervivek5/VigyBag/assets/133862694/7a5d37df-31f8-4863-b11e-f383d5267789

### CODE REVIEW

**Comment by PoulavBhowmick03** [comment]
@codervivek5 @JigarJoshi04 Please merge this.

**Comment by codervivek5** [comment]
kindly reduced the size so that it look like pretty...........adjust this page size without

**Comment by PoulavBhowmick03** [comment]
@codervivek5 I have made the changes
image

**Comment by codervivek5** [comment]
can you make ti somthing like this.

image

**Comment by codervivek5** [comment]
means add the basic details in left side

**Comment by PoulavBhowmick03** [comment]
Okay, would work on it

**Pull request closed without merging**
