### PR TITLE
Product page

### PR DESCRIPTION
**Pull request by essy16**
## Changes proposed
Added products page 

## Screenshots

https://github.com/codervivek5/VigyBag/assets/58663564/ccc735e8-5a4b-41c9-88c7-886d30437c38

## Note to reviewers

@07jasjeet please review

### CODE REVIEW

**Comment by codervivek5** [comment]
kindly solve the conflict

**Comment by codervivek5** [comment]
hello @07jasjeet 

kindly review this PR asap so that they can get their point if this PR will merge.

**Comment by 07jasjeet** [comment]
@essy16 Im not happy with alot of stuff here.
1) The paddings. Please default to 16.dp or multiples of 4.
2) Please check colors for both day and night themes before submitting work related to UI.
3) Please refer to other fragments for best practices. You have done most of the stuff right but not made use of the fragment class's constructor which eliminates a lot of boiler plate code.
4) Solve merge conflicts before asking for review :)

**Comment by essy16** [comment]
@07jasjeet wdym by number 3? and thank you for the corrections.

**Pull request closed without merging**
