### PR TITLE
Issue#18 created a login page

### PR DESCRIPTION
**Pull request by Saumya40-codes**
image

### CODE REVIEW

**Comment by codervivek5** [comment]
kindly refer this design:
https://www.figma.com/file/hXcM6chTK70O6rAqCTFxuc/VigyBag?type=design&node-id=12%3A2&t=0nBur8cxIfLXW2ie-1

**Comment by codervivek5** [comment]
at the time of PR kindly mention your issue number also.

**Comment by rv1830** [comment]
please assign this to me

**Comment by Saumya40-codes** [comment]
@codervivek5 I haven't worked with Figma style much. As a result, I'm not able to get the perfect output. Thus I have unassigned from this issue.

**Comment by codervivek5** [comment]
> @codervivek5 I haven't worked with Figma style much. As a result, I'm not able to get the perfect output. Thus I have unassigned from this issue.

it's ok.
Thank you for contribution :)

**Pull request closed without merging**
