### PR TITLE
Issue650: Responsive Website

### PR DESCRIPTION
**Pull request by akanksha984**
Issue #650 
Made the website responsive
image

### CODE REVIEW

**Comment by akanksha984** [comment]
@codervivek5 please review this

**Comment by codervivek5** [comment]
can you arrange product like this 
image

**Comment by akanksha984** [comment]
@codervivek5 ok

**Comment by akanksha984** [comment]
image

@codervivek5

**Comment by akanksha984** [comment]
@codervivek5 please check it

**Comment by codervivek5** [comment]
kindly solve conflict but before make any PR ....you can share your changes with me so that I can review it....

at this time it is not looking good share screen for iPhone 14 pro

**Comment by akanksha984** [comment]
I have tried my best but sorry @codervivek5 i am unable to find error in that rest all i have made responsive

**Comment by codervivek5** [comment]
due to the unstructured of website I have to revert it again .....please make again a new PR

**Pull request merged**
