### PR TITLE
[ADD] review carousel

### PR DESCRIPTION
**Pull request by spaul-12**
Screenshot from 2023-05-27 02-37-44

### CODE REVIEW

**Comment by spaul-12** [comment]
@codervivek5 Please review this feature and merge it.

**Comment by JigarJoshi04** [comment]
What are the sources of this images?
Please give due credit to the relevant sources for using their image.

**Comment by spaul-12** [comment]
@JigarJoshi04 I have used images from the website below:
https://www.pexels.com/search/people/

**Comment by JigarJoshi04** [comment]
I could not find any required citations to be added.
Approving the code.
Merging it.

**Review by JigarJoshi04 — APPROVED** [review]

**Pull request merged**
