### PR TITLE
Fixed The ChatBot is Overlapping to The Scroll to top Button

### LINKED ISSUE #1877: BUG: The Chatbot is Overlapping to Scrollbar Button
Hey @codervivek5 

On this website, the chatbot is overlapping to the scrollbar button

image

image

### The changes I will make
I would like to fix the issue by repositioning the scroll to top button besides chatbot button

**like this**

image

### PR DESCRIPTION
**Pull request by RadhikaMalpani1702**
Hey @codervivek5 

- issue closes #1877 

I have fixed the chatbot is overlapping to the scroll to top button

image

image

## Summary by CodeRabbit

- **Style Improvements**
	- Enhanced the visibility and accessibility of the 'GoToTop' button by repositioning it on the screen and increasing its stacking order.

### CODE REVIEW

**Comment by codervivek5** [comment]
is it possible to flip these button like chatbot will above to scroll to top button

**Comment by RadhikaMalpani1702** [comment]
@codervivek5

 > is it possible to flip these button like chatbot will above to scroll to top button

Yes I have tried it but the chatbot component is not custom coded it is inbuilt webchat by botpress, the one who added the chatbot can only make the changes in it as he/she only have the access to the webschat styles in their botpress dashboard

**Comment by codervivek5** [comment]
> @codervivek5
> 
> > is it possible to flip these button like chatbot will above to scroll to top button
> 
> Yes I have tried it but the chatbot component is not custom coded it is inbuilt webchat by botpress, the one who added the chatbot can only make the changes in it as he/she only have the access to the webschat styles in their botpress dashboard

ohh  so how can it will possible .... kindly check it in your local pc by register your self in chatbot site and test it if its work then I'll give you API key and other things which will required

**Comment by RadhikaMalpani1702** [comment]
@codervivek5  I don't have any inbuilt chatbot sites knowledge, the only solution is to ask the Contirbutor who made this chatbot (PR #1849 created by @antriksh-9 ) and tell him to Increase the margin from the bottom only

**Comment by antriksh-9** [comment]
> @codervivek5 I don't have any inbuilt chatbot sites knowledge, the only solution is to ask the Contirbutor who made this chatbot (PR #1849 created by @antriksh-9 ) and tell him to Increase the margin from the bottom only

I had already tried changing the position of the chatbot but couldn't find any solid solution. 
So, the alternative solution maybe to change the position of the back-to-top button, like shifting it to the left side.

**Comment by RadhikaMalpani1702** [comment]
@antriksh-9 Try to change in botpress webchat styler and then paste the stylesheet link in your botpress dashboard

**Comment by antriksh-9** [comment]
> @antriksh-9 Try to change in botpress webchat styler and then paste the stylesheet link in your botpress dashboard

That works for the older version of botpress, and I have created the bot from the latest version.

**Comment by RadhikaMalpani1702** [comment]
Hey @codervivek5 Please merge this PR  the changes I made are also fine

**Comment by RadhikaMalpani1702** [comment]
@codervivek5  Please merge this PR as the GSSOC is near to it's end

**Comment by codervivek5** [comment]
> @codervivek5 Please merge this PR as the GSSOC is near to it's end

have you fixed the place of the chatbot?

and don't worry about the contribution period. it will continue till 10

**Comment by codervivek5** [comment]
kindly show me if everything will fine then will ping you.

**Comment by RadhikaMalpani1702** [comment]
@codervivek5  No I am unable to access it

**Comment by codervivek5** [comment]
kindly share any screen shot of your current changes

**Comment by codervivek5** [comment]
Ok I'll assign this to another once maybe then can fix this

**Pull request closed without merging**
