### PR TITLE
Added Privacy Policy Page

### PR DESCRIPTION
**Pull request by SadafKausar2025**
## Fixes Issue #1151 

It is very important to add privacy policy page to vigybag website.

Screenshot (1776)

### CODE REVIEW

**Comment by SadafKausar2025** [comment]
Hey @codervivek5 
please merge this PR

**Comment by SadafKausar2025** [comment]
https://github.com/codervivek5/VigyBag/assets/137484958/dbca20c0-18bd-42c9-8f33-1d074bfd5432

**Review by SyedImtiyaz-1 — APPROVED** [review]
All Set !

**Comment by codervivek5** [comment]
Thankyou for your Contribution :)

**Pull request merged**
