### PR TITLE
Updated Footer

### PR DESCRIPTION
**Pull request by Sameep002**
Screenshot 2023-05-26 133220

this pr under issue #40 
@codervivek5 is this fine?

### CODE REVIEW

**Comment by codervivek5** [comment]
It looks good but make all the sections even so that it's perfect.

**Comment by Sameep002** [comment]
Screenshot 2023-05-26 222142

just showing for confirmation not updated repo code yet, if this ok will send new branch

**Comment by codervivek5** [comment]
Thank you for your contribution :)

**Comment by Sameep002** [comment]
You welcome!!

**Pull request merged**
