### PR TITLE
Started django project and added landing page files issue#62

### PR DESCRIPTION
**Pull request by harshit21-02**

### CODE REVIEW

**Comment by codervivek5** [comment]
kindly mention your issue number at PR time and show me the out put so that I can review and give you proper feedback

**Comment by codervivek5** [comment]
any update?

**Comment by harshit21-02** [comment]
issue number #62

**Comment by harshit21-02** [comment]
Screenshot 2023-05-25 013831

**Comment by codervivek5** [comment]
thank you for your contribution.

**Pull request merged**
