### PR TITLE
Added the Dark Theme

### PR DESCRIPTION
**Pull request by parasss19**
## Closes issue #608
- Applied in Dark mode with proper functionality 

## Original

https://github.com/codervivek5/VigyBag/assets/101205226/88a97f0d-6ca5-450f-a606-2086089b95dc

## Updated

https://github.com/codervivek5/VigyBag/assets/101205226/44dff617-4b84-457c-9be7-ea6ceb37e2f2

### CODE REVIEW

**Comment by parasss19** [comment]
Hey @codervivek5 Please review it once

**Comment by codervivek5** [comment]
first you pull the code then check if navigation take full width then ok but if it is not taken full width then plz fix this bug

**Comment by codervivek5** [comment]
kindly share any out put mobile responsive also

**Comment by parasss19** [comment]
> first you pull the code then check if navigation take full width then ok but if it is not taken full width then plz fix this bug

Hey @codervivek5 
- Pulled the changes
- Navigation take full width


https://github.com/codervivek5/VigyBag/assets/101205226/5249761b-9650-452a-8c90-c003ed5d160c

**Comment by codervivek5** [comment]
perfect 👍 

Thank you for your contributions

**Pull request merged**
