### PR TITLE
fix: Added Multiple Properties to Improve Enhancement in Footer Area Elements

### PR DESCRIPTION
**Pull request by NarendraKoya999**
## Changes proposed
- **Added Hovering Effects along with Transformation on Payments Image.**
- **Also, added font-size to Copyright Text.**

## Note to reviewers
- **These above Changes are Made and Working Correctly without Errors.**

### CODE REVIEW

**Comment by NarendraKoya999** [comment]
Hi @codervivek5 . Please Review on this PR and Add Valid Level Label under GSSOC'23. Thank You !

**Comment by codervivek5** [comment]
can you please share any output ?

**Comment by NarendraKoya999** [comment]
> can you please share any output ?
@codervivek5 . Check this Output?

https://github.com/codervivek5/VigyBag/assets/84512164/78881b9a-4b50-4f66-9913-371f68faf484

**Comment by codervivek5** [comment]
I am sorry but do not add this effect in the pay buttons.
if possible then decrease the height of footer and make it responsive

**Comment by NarendraKoya999** [comment]
> I am sorry but do not add this effect in the pay buttons. if possible then decrease the height of footer and make it responsive

You did not Observe Even Copyright Text also @codervivek5 . You did not read My Issue Description Properly. @codervivek5

**Comment by codervivek5** [comment]
there is no need to make these change...I read your description but I was thinking that you can make more changes on it....if you can make changes which i provide you in previous message then plz go through it

**Comment by NarendraKoya999** [comment]
> there is no need to make these change...I read your description but I was thinking that you can make more changes on it....if you can make changes which i provide you in previous message then plz go through it

Ok @codervivek5 . I can End with this Chat. I am not Interested to Develop your Suggested Feature. Finally, Thank You for Giving Valuable Contributing Period given Me.

**Pull request closed without merging**
