### PR TITLE
✅✅Improved Home page with new eco-friendly design🚀 -  #1063

### LINKED ISSUE #1063: Change full Home page design
Description : 
I want to change Home page design and responsiveness . and make it eye catching and attractive.

Hello @codervivek5 ,
Please assign me this issue , i want to work on it.
image

### PR DESCRIPTION
**Pull request by dhruv389**
This pull request is regarding the issue number : #1063 

Closes #1063 

## Changes proposed
i improved whole home page with eco friendly theme   according new Figma design in **react-js** ,in which all products are hand made  then  according your requirements   i have made below changes in home page. **And  also make it responsive for all devices.**

## Screenshots

**After the Changes Home page looks like this :**

Screenshot 2024-05-20 012505

**Please merge this pull request**

### CODE REVIEW

**Comment by dhruv389** [comment]
Hello @codervivek5 ,
 please check out  this pull request.

**Comment by dhruv389** [comment]
Hello @codervivek5 ,
please check out this pull request.

**Comment by dhruv389** [comment]
Hello @codervivek5 ,
can you merge this pull request.

**Comment by codervivek5** [comment]
@dhruv389 sorry for late responce.

you design is perfect but there is a little bit changes we planned for resigning this with other tech stack like React Js so if possible try to re-code it in react

you can check the folder structure I have added a folder **front-with-react**. you can get a sample code structure and start working on there 

If you have any issue or query then feel free to ask me

**Comment by dhruv389** [comment]
Hello @codervivek5 ,


### I Written whole Code in react js in  folder of  front-with-react.  , and i have also made Best  folder structure in  front-with-react and routes and many more in that folder , So just checkout my changes in front-with-react folder. 

### And Merge this Pull request.

**Comment by dhruv389** [comment]
### You Can start new website in  react js  from  that folder . I have done all Set up whole  structure in front-with-react Folder.

**Review by dhruv389 — COMMENTED** [review]
done

**Pull request closed without merging**
