### PR TITLE
feat: add codeql workflow

### PR DESCRIPTION
**Pull request by harmeetsingh11**
## Related Issue
This PR closes issue: #426 

### Files added
- `.github/workflows/codeql.yml`

### To run this workflow you need to enable the following permission:

1. **Go to your project repository settings**
2. **On left pane > Actions > General**

image

3. **Scroll down and Go to Workflow permissions > select "Read and write permissions"**

image

4. **Click save and its done.**

Please review this PR.
Thanks

### CODE REVIEW

**Comment by codervivek5** [comment]
why it is failed all the PR after analyze

**Comment by codervivek5** [comment]
image

**Comment by codervivek5** [comment]
showing this issue all the time

**Comment by harmeetsingh11** [comment]
Ok. Autobuild fails with java. I'll check it out what's the issue.

**Comment by harmeetsingh11** [comment]
I tried to solve the issue, but the only thing we can do is remove `java` language from matrix. It could not find build for maven and gradle.

**Pull request merged**
