### PR TITLE
Fixed Search Button Styles

### LINKED ISSUE #1014: Enhancement: Search Input and Heading Text Alignment Issue on Home Page
### Description
On the home page of the application, there are two issues observed:
1. The search input is not displaying properly.
2. The heading text is not properly aligned.

### Expected Behavior
1. The search input should be visible and properly aligned on the home page.
2. The heading text should be correctly aligned with the rest of the content on the page.

### Steps to Reproduce
1. Navigate to the home page of the application.
2. Observe the search input and heading text alignment issues.

### Additional Context
These issues affect the visual appeal and usability of the home page. It's essential to address them to ensure a consistent and pleasant user experience across the application.

### Screenshot
Home Page

### PR DESCRIPTION
**Pull request by MishraTanishq619**
Closes #1014 

## Changes proposed

- Changed styles of input field, image and container div.
- made div element to relative,
- made serch icon absolute,
- adjusted sizes, padding, margin of container, icon and field.

## Screenshots
Screenshot from 2024-05-12 12-16-36
Screenshot from 2024-05-12 12-16-14
Screenshot from 2024-05-12 12-15-45

## Note to reviewers

I had reviewed this with many viewports. Remember to label GSSOC.
Thanking You.

### CODE REVIEW

**Comment by codervivek5** [comment]
use second one

**Comment by MishraTanishq619** [comment]
All are of a single commit.
3 pics are of 3 different screen-widths.

Issue is done by this PR.

Kindly Label the issue as GSSOC Plz..
Ths.

**Comment by ShristiSharan** [comment]
No conflicts!....reviewed

**Comment by codervivek5** [comment]
@ShristiSharan kindly connect with me via any social media like discord or LinkedIn or Insta.....I need to talk to you about this the mentorship

**Pull request merged**
