### PR TITLE
Major Alignment Issue fixed : {no functionality removed}

### PR DESCRIPTION
**Pull request by SyedImtiyaz-1**
### Hello @codervivek5  

- ### Fixes Issue #809 

## Changes done: 

1. Attached CSS
2. Added team files {css,js,html}
3. review col added again 
4. minifiied the style.css because taking too much time to reload because of the inappropriate CSS files
5. Added cart img 
6. Checked the previous commits and added new lines to the see more page js which was logic added by me.
7. script.js {main} upgraded

### Video 1

[Screencast from 10-08-23 01:54:38 PM IST.webm](https://github.com/codervivek5/VigyBag/assets/121503426/2e0af1a3-c9cc-4c8c-9088-7c7621998c89)

### Video 2
[Screencast from 10-08-23 01:55:25 PM IST.webm](https://github.com/codervivek5/VigyBag/assets/121503426/904d010d-5e25-49c3-b338-04e137204d8f)

## `important` Note to reviewers : Please pull the code before pushing and check files are linked or not because this habit damage the alignment.

```
@codervivek5 Thank You, It was a great 3 Months of journey.
``` 
- Closes Issue No #809

### CODE REVIEW

**Comment by codervivek5** [comment]
bro plz pull the code once then make changes ...also solve the conflict

**Comment by codervivek5** [comment]
kindly do not make any changes in review file

**Comment by SyedImtiyaz-1** [comment]
Sure @codervivek5

**Comment by codervivek5** [comment]
bro plz solve conflict

**Comment by SyedImtiyaz-1** [comment]
@codervivek5 Sorry for the delay I was busy.

**Comment by SyedImtiyaz-1** [comment]
## Conflicts are resolved now you can merge this.

**Comment by codervivek5** [comment]
> @codervivek5 Sorry for the delay I was busy.

No issue 😄

**Comment by SyedImtiyaz-1** [comment]
/

**Comment by SyedImtiyaz-1** [comment]
@codervivek5

**Pull request merged**
