### PR TITLE
Fixed Icons

### PR DESCRIPTION
**Pull request by Somesh-Mallewar**
Hello @codervivek5 ,
I have fixed the issue regarding icons in socials #457 .

## Screenshot -
icons

### CODE REVIEW

**Comment by codervivek5** [comment]
add your issue number plz

**Comment by Somesh-Mallewar** [comment]
Issue Number - #457
Please Check.

**Comment by Somesh-Mallewar** [comment]
@codervivek5 
Please Review My PR.

**Comment by codervivek5** [comment]
there is nothing in your PR........I can't see any changes which you make

**Pull request closed without merging**
