### PR TITLE
Products view page

### PR DESCRIPTION
**Pull request by Chavisn**
Here is the link of the code :
https://docs.google.com/document/d/11y2ZRZh9hW9v5KHRziqb17xSWp9LQepz5UwwcBBAAek/edit

This is Issue #99

### CODE REVIEW

**Comment by codervivek5** [comment]
provide me access for this so that I can see.

**Comment by Chavisn** [comment]
I am resharing this.
https://docs.google.com/document/d/11y2ZRZh9hW9v5KHRziqb17xSWp9LQepz5UwwcBBAAek/edit?usp=sharing

**Comment by codervivek5** [comment]
I suggest you for future PR don't do it like this. Take a screenshot and send me
I will  check you change form my side code

**Comment by Chavisn** [comment]
Ok.. I will keep this in mind.

**Comment by Chavisn** [comment]
And I wanted to know do I need to make additional changes..?

**Comment by Chavisn** [comment]
I am attaching the code for user profile page. Please check it

**Pull request merged**
