### PR TITLE
Product dropdown behavior issue resolved

### LINKED ISSUE #1629: [BUG] Dropdown-must-collapse-automatically
The dropdown must collapse automatically but it is staying these even I have chosen one option from it.

image

##Checklist

- [X] I am a GSSoC 2024 contributor.
- [X] I have checked for any existing issues
- [X] I want to work on this issue.

### PR DESCRIPTION
**Pull request by bhuvangoel04**
## Changes proposed

Now the products dropdown opens up when user brings mouse on 'Products' and collapses automatically.

## Summary by CodeRabbit

- **New Features**
  - Enhanced dropdown menu functionality with hover interactions in the navigation bar.

- **Style**
  - Minor whitespace adjustment in the "Fashion" link for consistency.

### CODE REVIEW

**Comment by codervivek5** [comment]
can you plz share output of that changes

**Comment by bhuvangoel04** [comment]
> can you plz share output of that changes

[VigyBag - Eco friendly store.webm](https://github.com/codervivek5/VigyBag/assets/156914582/46d1ef14-651e-4ea8-9727-8eda7ede81fc)

**Comment by codervivek5** [comment]
take a look of your changes it is not properly working in production code

**Comment by bhuvangoel04** [comment]
> take a look of your changes it is not properly working in production code

It was working perfectly working in production but a PR by Ansh101112 merged to change navbar properties changed my code in his commit.

**Comment by bhuvangoel04** [comment]
My code was working perfectly fine.

image


See this is the change he has done.

**Comment by bhuvangoel04** [comment]
This is causing the issue.

**Pull request merged**
