### PR TITLE
Contact US Page modified

### PR DESCRIPTION
**Pull request by Pragati-3003**
@codervivek5 , I have modified the UI  of the contact us page ,please review and merge the PR.
Closes#701

### CODE REVIEW

**Comment by codervivek5** [comment]
kindly solve the merge conflict and also attach an output and also mention the issue number with a space so that it can work

**Comment by codervivek5** [comment]
can you share any output

**Comment by Pragati-3003** [comment]
> kindly solve the merge conflict and also attach an output and also mention the issue number with a space so that it can work
Issue #701
image

**Comment by codervivek5** [comment]
can you add some more changes...like adding social media icons

**Comment by codervivek5** [comment]
you can get links form readme file

**Comment by Pragati-3003** [comment]
> can you add some more changes...like adding social media icons

okie,I'll

**Comment by codervivek5** [comment]
add FAQ section below to it

**Comment by codervivek5** [comment]
image
chech this one

**Comment by Pragati-3003** [comment]
> image chech this one

@codervivek5 , Ig it would be good if you add  the "Inbox section to the footer" , this will increase the User experience , although I will add the customer service number and social links to the form

**Comment by codervivek5** [comment]
ok I will share this information with footer contributor

**Comment by Pragati-3003** [comment]
image
@codervivek5 , I have modified the contact us page as per your requirements, Please review and merge the PR..

**Review by codervivek5 — APPROVED** [review]

**Pull request merged**
