### PR TITLE
Modified the style.css

### PR DESCRIPTION
**Pull request by debrajrout**
# Changed the style.css file

### All changes are done in both dark and light mode

### CODE REVIEW

**Comment by codervivek5** [comment]
can you share any output of your change ?

**Comment by debrajrout** [comment]
https://github.com/codervivek5/VigyBag/assets/99877936/a1b79855-2dcf-495b-9fb7-e5ca178a893d

**Comment by debrajrout** [comment]
These are the changes I made.

**Review by codervivek5 — APPROVED** [review]

**Comment by codervivek5** [comment]
Thankyou for your contribution ❤️.
You can share this change in LinkedIn and tag me also  use #VigyBag.

**Pull request merged**
