### PR TITLE
Made the website usable for phone

### PR DESCRIPTION
**Pull request by afeefuddin**
Solves issue #10 

I made the website usable for phone and it works till the width of mobile 342px (90 percent smart phone)

If we want to make it usable for more thinner Smart phone, we have to make a new nav bar with toggle button.

We can work on it as a separate issue.

### CODE REVIEW

**Comment by codervivek5** [comment]
if you make any change then send me output so that I can review it.

**Comment by codervivek5** [comment]
if you make any changes then send me the output so that I can review it.

**Comment by afeefuddin** [comment]
Screenshot (3)
Screenshot (4)
Screenshot (7)
Screenshot (6)
Screenshot (5)
Screenshot (12)
Screenshot (11)
Screenshot (10)
Screenshot (9)
Screenshot (8)
Screenshot (13)](https://github.com/codervivek5/VigyBag/assets/126336384/606e4032-2196-436a-b45f-5a7bc13ab7dc)
ps://github.com/codervive
Screenshot (15)
k5/VigyBag/assets/126336384/3083233a-a58e-4fd7-b0d8-bce4243b0f96)
Screenshot (16)
Screenshot (17)](https://github.com/codervivek5/VigyBag/assets/126336384/8a3f2d15-eab3-40f0-afc3-3d883d0b2584)
ithub.com/codervivek5/VigyBag/assets/126336384/3b68cb02-bc0e-4ac7-aec7-19467db6dab2)
Screenshot (19)
Screenshot (20)

**Comment by afeefuddin** [comment]
Hey @codervivek5 Uploaded the photos for different dimensions

**Pull request merged**
