### PR TITLE
Favicon added

### PR DESCRIPTION
**Pull request by VyjayantiN**
This pull request adds a favicon to the project, enhancing the overall user experience and branding. A favicon is a small icon that appears in the browser tab or bookmark bar, providing visual identification for the website.

The favicon has been carefully designed to align with the project's branding guidelines and reflect its unique identity. It adds a professional touch to the website and helps users easily identify and differentiate it among their open tabs.

By merging this pull request, the project will have an enhanced visual presence, reinforcing its branding and providing a polished user experience.

### CODE REVIEW

**Comment by VyjayantiN** [comment]
I have made some updates to the footer section of our website and I would like to submit a pull request to incorporate these changes. The modifications include adding appropriate icons for the contact information, formatting the address for better readability, and improving the overall spacing and alignment.

Please review the pull request at your convenience. I appreciate your time and consideration.
image

**Comment by s4shantanu** [comment]
I already resolve this issue please check issue no.  #309 

https://github.com/codervivek5/VigyBag/pull/309

**Comment by VyjayantiN** [comment]
@codervivek5 Please look into it!!

**Comment by VyjayantiN** [comment]
@codervivek5 Please check this out!!

**Pull request closed without merging**
