### PR TITLE
Update index.html Resolve Issue No. #89

### PR DESCRIPTION
**Pull request by s4shantanu**
Resolve Issue number #89 
Correct the spelling from card to cart.

### CODE REVIEW

**Review by s4shantanu — COMMENTED** [review]
Please Review and Approve my PR @codervivek5 :)

**Comment by codervivek5** [comment]
can i show the output

**Comment by s4shantanu** [comment]
> can i show the output

Sure!!

Before - 

Screenshot 2023-05-22 at 4 51 53 PM


After - 

Screenshot 2023-05-22 at 4 51 19 PM

**Comment by s4shantanu** [comment]
Please review and merge the PR. :)  @codervivek5

**Comment by codervivek5** [comment]
kindly solve merge conflict

**Comment by s4shantanu** [comment]
Done <3 
Now Looks Good to me!

**Pull request merged**
