### PR TITLE
Fixed text visiblity in contact form 

### LINKED ISSUE #937: [Issue] : Enhance Message Input Visibility
### Issue Description:
The text typed into the message input box in the "Contact Us" section is not visible, likely due to insufficient contrast with the background. This makes it challenging for users to see what they are typing.

I would like to request a change in the text color within the message input box to ensure better visibility. 

### Screenshot:
Screenshot 2024-01-19 125402

**Working under JWoC'24**

### PR DESCRIPTION
**Pull request by Tanishka023**
## Fixes Issue 

Closes #937 

## Changes proposed

Made changes in contact.css for better text visibility

### CODE REVIEW

**Comment by codervivek5** [comment]
kindly mention the issue number and screenshot also so that I can see and review it properly

**Comment by Tanishka023** [comment]
> kindly mention the issue number and screenshot also so that I can see and review it properly 

I have done the needful, really sorry for the inconvenience.

**Comment by codervivek5** [comment]
kindly share a screenshot so that I can review and  merges successfully

**Comment by Tanishka023** [comment]
> kindly share a screenshot so that I can review and  merges successfully

Here!

**Comment by codervivek5** [comment]
Kindly make these changes 
 - make an even rounded blue box in every corner.
 - add padding even on both sides -> left and right
 - add some space below the submit so that it will like professional
 - increase size of logo little bit more
 - if there is no any footer then use home page footer and add that also

after make these change kindly share output again so that I can review

**Comment by Tanishka023** [comment]
> Kindly make these changes 
>  - make an even rounded blue box in every corner.
>  - add padding even on both sides -> left and right
>  - add some space below the submit so that it will like professional
>  - increase size of logo little bit more
>  - if there is no any footer then use home page footer and add that also
> 
> after make these change kindly share output again so that I can review 

Sure!
The previous changes are good?

**Comment by Tanishka023** [comment]
image
Have started working on these! Take a look please 

Completed- 
- [x] increase logo size
- [x] added padding
- [x] space below submit button
- [x] also, a footer already exists in the contact page

**Comment by codervivek5** [comment]
@Tanishka023  can you make look like this 

image
image

**Comment by codervivek5** [comment]
choose any one ...... kindly let me know if you can make it asap

**Comment by Tanishka023** [comment]
> choose any one ...... kindly let me know if you can make it asap

Hey!! I have made the necessary changes, just a minute

**Comment by codervivek5** [comment]
sure

**Comment by Tanishka023** [comment]
> choose any one ...... kindly let me know if you can make it asap

I think it already looks similar to the second one, I just need to add "Phone number" and "Address", this can be done ✅

**Comment by codervivek5** [comment]
> > choose any one ...... kindly let me know if you can make it asap
> 
> I think it already looks similar to the second one, I just need to add "Phone number" and "Address", this can be done ✅

yes but check color correction

**Comment by codervivek5** [comment]
make corner rounded and fix other issue

**Comment by Tanishka023** [comment]
> > > choose any one ...... kindly let me know if you can make it asap
> > 
> > I think it already looks similar to the second one, I just need to add "Phone number" and "Address", this can be done ✅
> 
> yes but check color correction 


Hey!! Can I create another issue for this and then start working?? 

image


Take a look, please. I think it looks good.
Can I make a new issue and merge?
@codervivek5 


Any inputs? @codervivek5

**Comment by codervivek5** [comment]
now it look like good but need to improve... I will merge it but kindly raised new issue to improve this and fix it

**Comment by codervivek5** [comment]
Thank you for your contribution :)

**Comment by Tanishka023** [comment]
> Thank you for your contribution :)

@codervivek5 Can you please add labels to this PR?

**Comment by Tanishka023** [comment]
> Thank you for your contribution :)

@codervivek5 Hey!! This was the first issue I was assigned for GSSoC but as I was assigned before 7pm that day, this is not getting counted, can something be done anyhow?

**Pull request merged**
