### PR TITLE
Added borders to product detail page

### LINKED ISSUE #2346: Added borders to product detail page
corrected the border of the products view page

### PR DESCRIPTION
**Pull request by SadafKausar2025**
## Fixes Issue #2346

Closes #2346

## Screenshots
before:
Screenshot (2498)

after:
Screenshot (2497)

## Summary by CodeRabbit

- **New Features**
	- Improved visual presentation of product images with new background color and border styles.
	- Enhanced layout for product price display for better readability.
	- Streamlined rendering of action buttons for a more concise user experience.

- **Bug Fixes**
	- Adjusted conditional rendering in product details for clearer availability and warranty information.

- **Style**
	- Refined the structure of various components for improved readability and consistency in rendering customer feedback and product ratings.
	- Simplified the "Add to Cart" button by removing unnecessary elements, maintaining core functionality.

### CODE REVIEW

**Comment by codervivek5** [comment]
Make image border darker look like logo dark color....it's not looking good

**Comment by SadafKausar2025** [comment]
Screenshot (2500)

**Comment by SadafKausar2025** [comment]
Screenshot (2501)

**Comment by AKSHITHA-CHILUKA** [comment]
add level labels @codervivek5

**Pull request merged**
