### PR TITLE
Update search bar

### LINKED ISSUE #851: Reduced height of search option
Screenshot 2023-09-26 at 1 02 06 PM

### PR DESCRIPTION
**Pull request by KUNDAN1334**
## Changes proposed

just reduced the height of search option.

### CODE REVIEW

**Comment by codervivek5** [comment]
kindly share your change so that I can review and give you possible feedback

**Comment by KUNDAN1334** [comment]
https://github.com/codervivek5/VigyBag/pull/863/commits/a04bc71ad615703a37a988d0c4274e1518ac4753

**Comment by KUNDAN1334** [comment]
please merge it after 1 0ct so that it will count in hacktoberfest

**Comment by codervivek5** [comment]
> please merge it after 1 0ct so that it will count in hacktoberfest

ok remind me once

**Comment by KUNDAN1334** [comment]
now you can merge.

**Comment by codervivek5** [comment]
Thank you for your contribution

**Comment by codervivek5** [comment]
share your changes bcz there are no any changes for review ........check it once plz

**Pull request merged**
