### PR TITLE
Update Product-PopUp

### PR DESCRIPTION
**Pull request by SyedImtiyaz-1**
Hello @codervivek5 ,
Issue No #695 
I have fixed the popup issue regarding the Product Section.

### Screenshot - 
Screenshot from 2023-07-29 21-00-15

### It is ready to merge 👍🏻

### CODE REVIEW

**Comment by codervivek5** [comment]
can you make some modifications to it? like in this pop-up page, you will provide basic detail of the product

**Comment by SyedImtiyaz-1** [comment]
Okay @codervivek5 ,
So I have replace lorem with specifications right ?
or you're asking something else ?

**Comment by codervivek5** [comment]
no no no ...you don't need to lorem text ....just make a template of the product detail. like title, price, description and below two button **add to cart** , **add to wishlist**

**Comment by SyedImtiyaz-1** [comment]
@codervivek5 Okay got it, will raise a PR soon.

**Pull request closed without merging**
