### PR TITLE
FAQ section created

### PR DESCRIPTION
**Pull request by Pragati-3003**
I have created FAQ section for the website.
Please review and merge and if you wanna any other changes than please inform me.
Fixes#327.
Screenshot 2023-06-08 142852

### CODE REVIEW

**Comment by JigarJoshi04** [comment]
Please add reviewers in the review section from the next PR.
Also you can assign the PR to your self.
You can also link the issue to PR.
Thanks for great contribution, keep up the good work.

**Review by JigarJoshi04 — APPROVED** [review]
Approving placeholder changes as there is literally no flow currently in our system.
This will remain placeholder changes.

**Comment by Pragati-3003** [comment]
> Please add reviewers in the review section from the next PR. Also you can assign the PR to your self. You can also link the issue to PR. Thanks for great contribution, keep up the good work.

Hey @JigarJoshi04 ! , I have raised issue #373 for the same , so please assign issue to me.

**Comment by Pragati-3003** [comment]
> 


> Approving placeholder changes as there is literally no flow currently in our system. This will remain placeholder changes.

Okie .

**Comment by codervivek5** [comment]
@Pragati-3003 kindly solve merge conflict then I will merge your PR.
you work good :)

**Comment by Pragati-3003** [comment]
> @Pragati-3003 kindly solve merge conflict then I will merge your PR. you work good :)

I have resolved  all the merge conlicts ,please check and merge my PR.

**Comment by codervivek5** [comment]
Thankyou for contribution :)

**Pull request merged**
