### PR TITLE
#398  Adding Navigation Host for Navigation in VigyBag App

### PR DESCRIPTION
**Pull request by javaman97**
Added Navigation Graph using Nav Host for Navigation in VigyBag Android App

### CODE REVIEW

**Comment by 07jasjeet** [comment]
I think you may have messed up your branch. There shouldn't be so many commits. Please make a new branch from main AFTER updating main from origin and origin from upstream. You can transfer your work to the new branch using git cherry-pick commit.

**Comment by essy16** [comment]
Hello @javaman97  have you created the Navigation graph I need it to so as to use it on the Bottom nav

**Comment by 07jasjeet** [comment]
> Hello @javaman97 have you created the Navigation graph I need it to so as to use it on the Bottom nav

@essy16 you can also create navigation graph yourself if you want. I can merge your work as well if done on properly and on time. Please don't be held back by other contributors.

**Comment by essy16** [comment]
> Added Navigation Graph using Nav Host for Navigation in VigyBag Android App

@javaman97  Your code is okay but what you did was just implement navigation between fragments
The steps you should have made was:
i)Include the correct navigation dependencies
ii)Create a navigation graph
iii)Add destinations to the navigation graph
iv)Add a NavHostFragment via XML
For more information here is the link: https://developer.android.com/guide/navigation/get-started
Hope this helps

**Comment by javaman97** [comment]
@essy16 I have already gone through the things you mentioned above. 
I have already implemented these things. Soon I will fix all other commits that are creating a mess.

**Comment by essy16** [comment]
@javaman97 i created a pr already with the above changes

**Comment by 07jasjeet** [comment]
> @essy16 I have already gone through the things you mentioned above. I have already implemented these things. Soon I will fix all other commits that are creating a mess.

@javaman97 change the merge head from development to main

**Comment by 07jasjeet** [comment]
nvm i have access.
@javaman97 I can't see your code anywhere. Are you sure you this is the branch you did work in?

**Comment by javaman97** [comment]
**@07jasjeet Yes feature_login is the same branch where I have implemented the NavHost**

nav4
nav3
nav2
nav1

**Comment by 07jasjeet** [comment]
> @07jasjeet Yes feature_login is the same branch where I have implemented the NavHost

I think you forgot to push your changes.

**Comment by javaman97** [comment]
@07jasjeet So,I need to make another commit and push for it ?

**Comment by 07jasjeet** [comment]
> @07jasjeet So,I need to make another commit and push for it ?

You seem to be in a messy git situation i think. Not sure what's happening on your local. You can create another pr if you want.

**Pull request closed without merging**
