### PR TITLE
Added hover effects on scrollbar thumb

### LINKED ISSUE #1575: Add hover effects on scrollbar thumb
image

By adding hover effects user can feel that he/she holding the scrollbar.
I will also add cursor pointer.

### PR DESCRIPTION
**Pull request by zalabhavy**
## Fixes Issue

Closes #1575

## Changes proposed

Added hover effects code in index.css where code of scrollbar is present.

## Screenshots

**When hover on it light black shadow on thumb will visible and cursor pointer i have added.**

image

## Summary by CodeRabbit

- **Style**
  - Enhanced scrollbar appearance with hover effects, including updated background, box shadow, and cursor properties for a better user experience.

### CODE REVIEW

**Comment by zalabhavy** [comment]
@codervivek5 Please check it and merge !

**Thank you !**

**Comment by zalabhavy** [comment]
@codervivek5 Please check it !

**Comment by codervivek5** [comment]
it means when user is hover at the scroll bar side then they can visible to scrollbar ?

**Comment by codervivek5** [comment]
I have assign this issue to you  ?

**Comment by zalabhavy** [comment]
@codervivek5 Yes , user can see scrollbar but some light layer on scrollbar's thumb will be visible so user can feel that holding  and cursor property set to pointer.

image

**Comment by zalabhavy** [comment]
@codervivek5 Please check it and merge !

**Thank You !**

**Comment by zalabhavy** [comment]
@codervivek5 want to merge ?

**Pull request merged**
