### PR TITLE
Android: Sign-in and sign-up UI improvement

### LINKED ISSUE #567: Android: Improve sign-up and sign-in UI
Sign-up / sign-in fragments could use some UI improvements in VigyBag Android App.

### PR DESCRIPTION
**Pull request by essy16**
@07jasjeet please review

### CODE REVIEW

**Comment by 07jasjeet** [comment]
@essy16 put the concepts I told you to use as you have merge conflicts again. This one should be easy. Also your uploaded screenshot is not visible.

**Comment by essy16** [comment]
@07jasjeet I have solved the conflicts kindly review

**Comment by 07jasjeet** [comment]
@essy16 good work! The conflicts seem to have been fixed.

Few fixes I'd like to have before we merge:

## Problem set 1:
In the image below, the colored arrow markers mean the following:

**Red:** Fix margins. Margins should be equal all across. Adjust all margins accordingly if you'll be decreasing it.
**Bule:** Please change the purple accent to VigyBag to ColorSecondary as in the colors file.

image

## Problem set 2:

The landscape views of both sign in and sign up are broken. Please fix them :)

image

**Comment by essy16** [comment]
image
@07jasjeet please review

**Comment by 07jasjeet** [comment]
@essy16 there are conflicts again, please resolve :)

**Comment by essy16** [comment]
I tried to merge and it's said merge already up to date

**Comment by essy16** [comment]
I have shown it in the picture

**Comment by 07jasjeet** [comment]
I have solved the conflicts for now but please try to solve conflicts yourself. Try going through git concepts again. Install GitHub Desktop, it really helps.
Other than the git problems, you work lgtm. Nice job!

**Pull request merged**
