### PR TITLE
about us page is updated

### PR DESCRIPTION
**Pull request by Sushilverma002**
## Fixes Issue

 Closes issue-> #857 

## Screenshots

https://github.com/codervivek5/VigyBag/assets/114687502/cc66faca-fccb-48f5-8c13-1e5aa466ab4d

## Note to reviewers
hackoctoberfest

### CODE REVIEW

**Comment by Sushilverma002** [comment]
@codervivek5 have a look!!

**Comment by Sushilverma002** [comment]
@codervivek5 have a look!!!!!!!!

**Comment by codervivek5** [comment]
kindly make it attractive line fix margin and padding and most change the color according to the theme color of website

**Comment by Sushilverma002** [comment]
https://github.com/codervivek5/VigyBag/assets/114687502/83a1e99c-4465-4bb9-9d44-53ad13fbd495

@codervivek5 now check!!!!!!!!

**Comment by Sushilverma002** [comment]
@codervivek5 have a look!!

**Comment by Sushilverma002** [comment]
@codervivek5 please have a look!!!!

**Comment by codervivek5** [comment]
can you plz make some changes like change heading color to oragiss or try to make it white?.
reduces the first para text a little bit.

**Comment by Sushilverma002** [comment]
updates done have look @codervivek5 

https://github.com/codervivek5/VigyBag/assets/114687502/a743ef01-fc4b-4e81-9395-2efed4f16561

**Comment by Sushilverma002** [comment]
@codervivek5

**Comment by codervivek5** [comment]
image
what is it mean ??? make color white

image
match font with home page

**Comment by codervivek5** [comment]
image
make it white

image
 Add a hypher - btw blck and white text

**Comment by Sushilverma002** [comment]
> image what is it mean ??? make color white
it means what makes use unique.
> 
> image match font with home page

**Comment by Sushilverma002** [comment]
image
it means what make us unique.

**Comment by Sushilverma002** [comment]
okkk changes done @codervivek5.

https://github.com/codervivek5/VigyBag/assets/114687502/ffe8f7a6-4f97-48c6-95c1-0640db1d148b

**Comment by Sushilverma002** [comment]
@codervivek5 have look please.

**Comment by Sushilverma002** [comment]
@codervivek5 have a look!!!!!!!!!!

**Comment by Sushilverma002** [comment]
@codervivek5 have a look!!!!!!!

**Comment by Sushilverma002** [comment]
@codervivek5

**Comment by Sushilverma002** [comment]
@codervivek5 please review my pr

**Comment by Sushilverma002** [comment]
@codervivek5 please tell me at least yes/no like you are gonna merge this pr or not. at least respond.

**Pull request closed without merging**
