### PR TITLE
Made the changes in the cart

### LINKED ISSUE #1593: Already the cart is with the items
There are items already in the cart before adding any thing

### PR DESCRIPTION
**Pull request by Saipradyumnagoud**
## Fixes Issue  

closes #1593
## Changes proposed
Made the changes in the cart component

## Screenshots
image

## Summary by CodeRabbit

- **New Features**
  - Replaced the item removal button with a Lordicon component for better user experience.
  - Restructured coupon input and actions UI elements for a cleaner layout.
  - Modified the layout for Clear Cart and Check Out buttons for improved navigation.

### CODE REVIEW

**Comment by codervivek5** [comment]
- change this delete icon color to red and make it a little bit small
- place check out button below to apply coupon 
- placed apply coupon to redeem and next to input field

**Comment by Saipradyumnagoud** [comment]
@codervivek5 please check now

**Comment by codervivek5** [comment]
kindly share your updated changes

**Comment by Saipradyumnagoud** [comment]
@codervivek5 can see now

**Review by codervivek5 — APPROVED** [review]

**Pull request merged**
