### PR TITLE
<modified the margins and padding between different sections and with…

### PR DESCRIPTION
**Pull request by PrachiChauhan23**
#104

### CODE REVIEW

**Comment by codervivek5** [comment]
kindly attach the output so that i can review

**Comment by PrachiChauhan23** [comment]
i got the merge conflict because i didn't make new branch while i was working on the issue. Then i deleted everything from my laptop and cloned it again and created new branch and as i committed that before so changes were there . I made the pr again then there was no conflict. Will it be considered??

**Comment by PrachiChauhan23** [comment]
> kindly attach the output so that i can review

sir do i have to attach code output?

**Comment by PrachiChauhan23** [comment]
sir it is again showing conflicting. what to do now?

**Pull request closed without merging**
