### PR TITLE
Added styles to the about us page #1168

### LINKED ISSUE #1168: Adding styles to the about us page
Adding styles to the about us page
@codervivek5 Please assign me this under GSSoC 2024

### PR DESCRIPTION
**Pull request by SuhainaFathimaM**
## Fixes Issue
Closes  #1168 

## Changes proposed

1. corrected footer of the about Page
2. Turned off text selection
3. added copyrights selection
4. added payments image
5. added colour to button
6. added hovering effect to button
7. Changed the content for header
8. Added style for the header topic
9. Changed the description content
10. Added style to description
11. Changed the about image

## Screenshots

image

image

## Note to reviewers

@codervivek5 I am contributing under GSSoC24 .. Please assign me this PR under GSSoC and label this PR

### CODE REVIEW

**Comment by SuhainaFathimaM** [comment]
@codervivek5 As you said, I have updated the image

**Comment by codervivek5** [comment]
is this page responsive ?

**Comment by codervivek5** [comment]
can you plz customize this page like this 
image

**Comment by SuhainaFathimaM** [comment]
@codervivek5 
Yes the page is responsive

image


image

Styling the page like that image you have given would make that page alone look different from other pages

**Comment by SuhainaFathimaM** [comment]
@codervivek5  Please merge this PR and label it under GSSoC

**Comment by SuhainaFathimaM** [comment]
@codervivek5 Please add level label to this PR as it would be considered by GSSoC

**Pull request merged**
