### PR TITLE
Fixes #975

### LINKED ISSUE #975: About us page
Screenshot 2024-05-09 at 3 21 01 PM

Read more is not not showing anything  when i click on it.
i will add  more text 
so when we  we click on read more .it will show more text .

please assign me this issue under GSSOC tag

### PR DESCRIPTION
**Pull request by sidhigrover**
## Fixes Issue
#975

## Changes proposed
Added counters for displaying relevant information.

## Screenshots

Screenshot 2024-05-29 at 1 21 11 AM

## Note to reviewers
Please suggest changes regarding the information added by my side.

### CODE REVIEW

**Comment by codervivek5** [comment]
Sidhi it's not looking nice ... Just take a reference of online images then try to recreate it

**Comment by sidhigrover** [comment]
> Sidhi it's not looking nice ... Just take a reference of online images then try to recreate it

Screenshot 2024-06-01 at 2 44 09 AM

now how it is looking?
the numbers which i add will appear like counter

**Comment by sidhigrover** [comment]
> Sidhi it's not looking nice ... Just take a reference of online images then try to recreate it

Screenshot 2024-06-01 at 3 17 52 AM


now how it is looking?
the numbers which i add will appear like counter
@codervivek5

**Comment by sidhigrover** [comment]
@codervivek5 sir please check

**Comment by sidhigrover** [comment]
> Sidhi it's not looking nice ... Just take a reference of online images then try to recreate it

sir.....please see it @codervivek5

**Pull request closed without merging**
