### PR TITLE
Adding Facebook Authentication

### LINKED ISSUE #2101: Adding Facebook Authentication
@codervivek5 I want to add Facebook Authentication to website. Kindly assign me this issue.

### PR DESCRIPTION
**Pull request by Ojas-Arora**
## Changes proposed

@codervivek5 I have added the Facebook Authentication yo the website. U just need to do the following steps:-
Go to Firebase Console.
Create a new Project with name VigyBag.
Get yor own Firebase Sdk file containing the Api Keys.
Add the Api Keys into the Firebase.js file.
Allow the authentication for Facebook from the Authentication Option.

## Summary by CodeRabbit

- **New Features**
  - Introduced Facebook authentication for social login via Firebase.
  - Added Firebase as a dependency to support enhanced features like real-time database and cloud storage.
  - Created a new `firebase.js` file to streamline Firebase authentication setup.

- **Bug Fixes**
  - Improved layout alignment for "Remember me" and "Forgot password?" elements to enhance user experience.

### CODE REVIEW

**Comment by codervivek5** [comment]
is it possible to add this functionality without Firebase

**Comment by Ojas-Arora** [comment]
@codervivek5 Not possible sir as I don't know any other feature to do so

**Comment by Ojas-Arora** [comment]
@codervivek5 Sir is this ok?

**Comment by codervivek5** [comment]
actually we was planning to do not use firebase that's why I was asking to you

**Comment by codervivek5** [comment]
https://www.scaler.com/topics/react/facebook-login-react/


try this one

**Comment by Ojas-Arora** [comment]
@codervivek5 Actually I am not aware of this but I will try to do so. It would take some more time if that's ok to you sir

**Comment by codervivek5** [comment]
Ok you can take your time ... But if possible then try to update me once a day

**Comment by Ojas-Arora** [comment]
@codervivek5 ok

**Comment by Ojas-Arora** [comment]
@codervivek5 Sorry sir but I am not able to do this. Kindly review this only. Sorry for the inconvenience.

**Comment by Ojas-Arora** [comment]
@codervivek5 Sir please tell because tomorrow is last day for gssoc

**Comment by codervivek5** [comment]
ok ..... kindly solve conflict then I'll merged

first pull the code then fix

**Comment by Ojas-Arora** [comment]
@codervivek5 done pls review

**Comment by Ojas-Arora** [comment]
@codervivek5 Please review this sir as soon as possible as Gssoc Deadline is there.

**Pull request merged**
