### PR TITLE
adjusted the chatbox to the screensize

### PR DESCRIPTION
**Pull request by Illaf**
closes issue #484
I later saw that the chatbot button started working on its own but then realized the chat box was going out of the screen as you can see in the screenshots. I have fixed it and tested on mobile mode also. I have seen several glitches for which i will be making more issues.
Initially
Screenshot (10)
after changes
Screenshot (12)

### CODE REVIEW

**Comment by Illaf** [comment]
Please tell if any further changes are required in this pr. thankyou

**Comment by Illaf** [comment]
@codervivek5 please merge this pull request

**Comment by codervivek5** [comment]
kindly solve merge conflict
after it i will merge it

**Comment by Illaf** [comment]
@codervivek5 Resolved the conflicts. you can merge now. Also please check the issue #518

**Comment by Illaf** [comment]
@codervivek5 The conflicts are resolved. Please merge this PR

**Comment by codervivek5** [comment]
kindly resolve the conflict then I will merge it

**Comment by ParthMadhvani2** [comment]
hey, please assign this task to me and merge my pull request. please

**Comment by Illaf** [comment]
> kindly resolve the conflict then I will merge it

sorry for the delay.was busy in a project . I will resolve them

**Comment by Illaf** [comment]
> hey, please assign this task to me and merge my pull request. please

it is better to create your own issues nd work on them :)

**Comment by Illaf** [comment]
@codervivek5  resolved the conflicts. Please merge it now

**Comment by codervivek5** [comment]
I am extremely sorry for it....actually a contributor upgrade this chatbot with an AI feature and also fix the minor UI.
so I will have to close this issue for now...you can plz move to another issue and work in that because if you worked on it then it will not be valuable.

again sry for it

**Pull request closed without merging**
