### PR TITLE
Feat: Send mail on contact submission

### LINKED ISSUE #1596: feat: Sending mail to owner on contact form submission
**Description**
Adding a feature where mail will be sent to owner when user submits the contact form to convey some message. This feature will send mail to owner that will contain the user's email address, and all the information that is filled in the form. This enhancement will improve user engagement. I will implement this feature using Emailjs.

@codervivek5 , please assign this issue to me under GSSoC'24

### PR DESCRIPTION
**Pull request by Ayesha-Siddiqua88**
## Fixes Issue
fixes #1596 

## Changes proposed
Added a feature of sending mails to owner when the user submits the contact form to improve user experience. The functionality is implemented using emailjs in contact.jsx file.

## Screenshots
form submitted and alert appears:
gssoc29

mail sent to owner in this format:
gssoc30

## Note to reviewers
Please review the changes made and merge it.

## Summary by CodeRabbit

- **New Features**
  - Enhanced the contact form to send emails using `emailjs.send`. Users will receive a success or error message upon form submission.

- **Bug Fixes**
  - Corrected event handling syntax in the navigation bar to improve user interaction on hover.

- **Chores**
  - Updated dependencies to ensure compatibility and stability of the application.

### CODE REVIEW

**Comment by codervivek5** [comment]
this feature is already added

**Comment by codervivek5** [comment]
kindly solve the conflict

**Comment by codervivek5** [comment]
pull the code first then try to solve

**Comment by Ayesha-Siddiqua88** [comment]
I've resolved the conflicts.

**Comment by codervivek5** [comment]
due to the multiple merge its happen again 
kindly solve this last time then I'll merge it

**Comment by Ayesha-Siddiqua88** [comment]
@codervivek5 resolved the conflicts.


okkk

**Pull request merged**
