### PR TITLE
fixed the images and icons

### LINKED ISSUE #497: In the home page, the photos in the headphone, tshirt and mobile section is disoriented
Currently in the home page, the photos go out of the container in which they are kept, that is for all the sections as you can see
image

image

image

I would like to make this right and fix it

### PR DESCRIPTION
**Pull request by PoulavBhowmick03**
Close #497 
Fixed the images and the icons that were disoriented previously

### CODE REVIEW

**Comment by PoulavBhowmick03** [comment]
@codervivek5 @JigarJoshi04 please merge this

**Review by JigarJoshi04 — APPROVED** [review]

**Comment by JigarJoshi04** [comment]
Great work,
Also for future add the relevant screenshots so that reviewer does not have to run the local setup.
Thanks for contributing.

**Comment by PoulavBhowmick03** [comment]
Ah my bad, would keep in mind from next time.
Also, can you please add a label to this @JigarJoshi04 .Thanks!

**Comment by PoulavBhowmick03** [comment]
@JigarJoshi04 @codervivek5 Please add a label to this once free

**Pull request merged**
