### PR TITLE
#377 Launcher Icon Added to VigyBag Android

### LINKED ISSUE #377: Add Launcher Icon to VigyBag Android
## A launcher icon is a graphic that represents your app to users.

_**I will add the Launcher Icon to our VigyBag Android App from one of the mentioned below shapes**_ 
### Different Shapes of Launcher Icon 

launcer_square
**Square**
launcher_circle
**Circle**
launcer_rectangle_wide
**Wide Rectangle**
launcer_rectangle
**Tall Rectangle**

### PR DESCRIPTION
**Pull request by javaman97**
### Added the Launcher Icon to VigyBag Android App
vigybag_launcher_icon

### CODE REVIEW

**Comment by javaman97** [comment]
@07jasjeet Please have a look and let me know if further changes required.

**Comment by 07jasjeet** [comment]
@javaman97 any way we can make the logo a bit bigger? Crop the original maybe?

**Comment by javaman97** [comment]
Alright, I will crop and make the padding to <5% as its padding is 10%

**Comment by 07jasjeet** [comment]
Please attach a photo of latest changes like you did previously.

**Comment by javaman97** [comment]
vigybag_large_icon

@07jasjeet Please have a look

**Comment by 07jasjeet** [comment]
Thanks for the work!

**Pull request merged**
