### PR TITLE
Updated Homepage Text Alignment

### PR DESCRIPTION
**Pull request by iamRabia-N**
This PR contains the code of updated Homepage Text Alignment.

### CODE REVIEW

**Comment by codervivek5** [comment]
@iamRabia-N can i see your output

**Comment by iamRabia-N** [comment]
### Current Alignment:
vigybag ss (1)

### Updated Alignment
vigybag ss (2)

**Comment by iamRabia-N** [comment]
If this alignment is approved, then I'll make this search area and image aligned according to the text and screen space so that the whole homepage design look consistent.

**Comment by iamRabia-N** [comment]
> ### Current Alignment:
> vigybag ss (1)
> 
> ### Updated Alignment
> vigybag ss (2)

@codervivek5

**Comment by iamRabia-N** [comment]
Hi @codervivek5 @JigarJoshi04 
Kindly review this PR so that I can work on other issues.

**Review by JigarJoshi04 — APPROVED** [review]

**Comment by codervivek5** [comment]
Kindly close the PR related to this issue so that you can get your points

**Comment by iamRabia-N** [comment]
@codervivek5 This PR is already closed although the related issue is open. Can I close the issue or the admins needs to close it?
Here is the issue related to this merged PR:
Homepage Text Alignment #244

**Comment by codervivek5** [comment]
Try to mention your issue number at PR time.so that Admin can close the issue along with PR

**Pull request merged**
