### PR TITLE
corrected the cards of the categories

### LINKED ISSUE #2326: Making the cards more correct in view
Screenshot (2494)

the cards here are not spaced properly

### PR DESCRIPTION
**Pull request by SadafKausar2025**
## Fixes Issue #2326

Closes #2326

## Screenshots
before:
Screenshot (2494)
after:
Screenshot (2492)

## Summary by CodeRabbit

- **New Features**
	- Introduced a "⚡Buy Now" button linking to the payment page, enhancing purchasing options.
- **Improvements**
	- Enhanced readability of product pricing and layout in the ProductGrid.
	- Adjusted button functionalities for better user interaction with wishlist and cart features.

### CODE REVIEW

**Comment by SadafKausar2025** [comment]
hello @codervivek5 
please review this PR and merge under hactoberfest 2024

**Comment by codervivek5** [comment]
Kindly add issue number

**Comment by codervivek5** [comment]
Kindly take a look of code rabbit code... When you fix it the let me know I'll merge it

**Comment by SadafKausar2025** [comment]
hello @codervivek5 
please merge this PR

**Review by codervivek5 — APPROVED** [review]

**Pull request merged**
