### PR TITLE
spinner added

### LINKED ISSUE #2092: Add a Loading Spinner--(Add a loading spinner for better user experience when data is being fetched)
Add a loading spinner for better user experience when data is being fetched.

### PR DESCRIPTION
**Pull request by arunimaChintu**
Closes #2092 

## Summary by CodeRabbit

- **New Features**
	- Introduced a new loading spinner component (`SPLoader`) to enhance user experience during authentication processes.

### CODE REVIEW

**Comment by arunimaChintu** [comment]
@codervivek5 Please merge this

**Comment by codervivek5** [comment]
take a look of code rabbit reviewed code and show the changes like which type of loader you have used

**Comment by arunimaChintu** [comment]
@codervivek5 done... Please merge this now..

**Comment by arunimaChintu** [comment]
@codervivek5 Please merge this...

**Pull request merged**
