### PR TITLE
added zoom in feature when hovering over images

### PR DESCRIPTION
**Pull request by shramanpaul**
added zoom in feature when hovering over images now the file can be merged.

### CODE REVIEW

**Comment by codervivek5** [comment]
kindly attach the output so that i can review

**Comment by shramanpaul** [comment]
Yes
1.hovering over the items make it zoom in
    
hovering over the items make it zoom in 2nd image

2. 
headphoness zoom in

**Comment by shramanpaul** [comment]
I have resolved the issues now it can be reviewed and merged

**Comment by codervivek5** [comment]
kindly solve the merge conflict but firstly pull the code then check if there will any changes then you can solve issue ....I will label is as level 3 after done this task

**Pull request closed without merging**
