### PR TITLE
Added Footer Properly

### PR DESCRIPTION
**Pull request by SyedImtiyaz-1**
Hello @codervivek5 ,
I have fix the error regarding the about us page.
Issue No. #697 

### Screenshot -
image

### It is ready to merge

### CODE REVIEW

**Comment by codervivek5** [comment]
kindly add some space between social icons and make these icons verticle with names and add a hover effect in the text...............bro if possible then reduced the height of the footer

**Comment by codervivek5** [comment]
add my linkedin pr instagram link the bottom copywrite - **Coder_Vivek**

https://www.instagram.com/coder_vivek/
https://www.linkedin.com/in/codervivek/

**Comment by SyedImtiyaz-1** [comment]
> kindly add some space between social icons and make these icons verticle with names and add a hover effect in the text...............bro if possible then reduced the height of the footer

okay

**Comment by codervivek5** [comment]
bro pull the code once then solve the conflict because we have to make a structure of unstructured pages...so do it once...

**Comment by SyedImtiyaz-1** [comment]
@codervivek5 You can merge this now .

image

**Comment by codervivek5** [comment]
kindly solve conflict then i will merge it

**Pull request closed without merging**
